import type { PracticeSeed } from "./types";

function step(order: number, text_fr: string, text_en: string, duration_seconds?: number) {
  return { order, text_fr, text_en, duration_seconds };
}

export const BREATHING_PRACTICES: PracticeSeed[] = [
  {
    slug: "breath-478-1min",
    category: "breathing",
    title: "Respiration 4-7-8",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["calme", "sommeil"],
    contraindications: ["grossesse_avis_medecin"],
    steps: [
      step(1, "Inspire par le nez 4 secondes.", "Inhale through nose 4 seconds."),
      step(2, "Retiens 7 secondes.", "Hold 7 seconds."),
      step(3, "Expire par la bouche 8 secondes.", "Exhale through mouth 8 seconds."),
      step(4, "Répète 3 cycles.", "Repeat 3 cycles."),
    ],
    i18n: { title: { fr: "Respiration 4-7-8", en: "4-7-8 breath" } },
    premium_only: false,
  },
  {
    slug: "breath-box-2min",
    category: "breathing",
    title: "Respiration carrée",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus", "calme"],
    contraindications: [],
    steps: [
      step(1, "Inspire 4 secondes.", "Inhale 4 seconds."),
      step(2, "Retiens 4 secondes.", "Hold 4 seconds."),
      step(3, "Expire 4 secondes.", "Exhale 4 seconds."),
      step(4, "Pause 4 secondes. Recommence.", "Pause 4 seconds. Repeat."),
    ],
    i18n: { title: { fr: "Respiration carrée", en: "Box breathing" } },
    premium_only: false,
  },
  {
    slug: "breath-coherence-5min",
    category: "breathing",
    title: "Cohérence cardiaque",
    duration_seconds: 300,
    intensity: "gentle",
    goal_tags: ["calme", "focus"],
    contraindications: [],
    steps: [
      step(1, "Inspire 5 secondes.", "Inhale 5 seconds."),
      step(2, "Expire 5 secondes.", "Exhale 5 seconds."),
      step(3, "Maintiens ce rythme régulier.", "Keep this steady rhythm."),
      step(4, "30 cycles ≈ 5 minutes.", "30 cycles ≈ 5 minutes."),
    ],
    i18n: { title: { fr: "Cohérence cardiaque", en: "Heart coherence" } },
    premium_only: false,
  },
  {
    slug: "breath-alternate-nostril-3min",
    category: "breathing",
    title: "Respiration alternée",
    duration_seconds: 180,
    intensity: "medium",
    goal_tags: ["focus", "calme"],
    contraindications: ["sinusite_aigue"],
    steps: [
      step(1, "Pouce droit sur narine droite.", "Right thumb on right nostril."),
      step(2, "Inspire par la narine gauche.", "Inhale through left nostril."),
      step(3, "Annulaire sur narine gauche, expire à droite.", "Ring finger on left nostril, exhale right."),
      step(4, "Inspire à droite, expire à gauche. Continue.", "Inhale right, exhale left. Continue."),
    ],
    i18n: { title: { fr: "Respiration alternée", en: "Alternate nostril" } },
    premium_only: false,
  },
  {
    slug: "breath-energizing-2min",
    category: "breathing",
    title: "Souffle énergisant",
    duration_seconds: 120,
    intensity: "medium",
    goal_tags: ["energie"],
    contraindications: ["hypertension", "grossesse_avis_medecin"],
    steps: [
      step(1, "Inspire courte par le nez (1s).", "Quick inhale through nose (1s)."),
      step(2, "Expire courte et active (1s).", "Quick active exhale (1s)."),
      step(3, "20 cycles puis pause normale 30s.", "20 cycles then normal pause 30s."),
      step(4, "Termine par 3 respirations lentes.", "End with 3 slow breaths."),
    ],
    i18n: { title: { fr: "Souffle énergisant", en: "Energizing breath" } },
    premium_only: false,
  },
  {
    slug: "breath-belly-1min",
    category: "breathing",
    title: "Respiration ventrale",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["calme", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Une main sur le ventre.", "One hand on the belly."),
      step(2, "Inspire en gonflant le ventre 4s.", "Inhale, expanding belly 4s."),
      step(3, "Expire en dégonflant 6s.", "Exhale, deflating 6s."),
      step(4, "6 cycles suffisent.", "6 cycles is enough."),
    ],
    i18n: { title: { fr: "Respiration ventrale", en: "Belly breath" } },
    premium_only: false,
  },
  {
    slug: "breath-sigh-30s",
    category: "breathing",
    title: "Soupir physiologique",
    duration_seconds: 30,
    intensity: "gentle",
    goal_tags: ["calme", "release"],
    contraindications: [],
    steps: [
      step(1, "Inspire long par le nez.", "Long inhale through the nose."),
      step(2, "Petite seconde inspiration en plus.", "Small extra second inhale."),
      step(3, "Expire long par la bouche.", "Long exhale through the mouth."),
      step(4, "Répète 3 fois.", "Repeat 3 times."),
    ],
    i18n: { title: { fr: "Soupir physiologique", en: "Physiological sigh" } },
    premium_only: false,
  },
  {
    slug: "breath-ujjayi-3min",
    category: "breathing",
    title: "Souffle de l'océan",
    duration_seconds: 180,
    intensity: "medium",
    goal_tags: ["focus", "calme"],
    contraindications: [],
    steps: [
      step(1, "Bouche fermée, légère contraction de la gorge.", "Mouth closed, slight throat contraction."),
      step(2, "Inspire long par le nez avec un son doux.", "Long inhale through nose with soft sound."),
      step(3, "Expire long par le nez avec le même son.", "Long exhale through nose with same sound."),
      step(4, "Le son ressemble à des vagues.", "Sound resembles waves."),
    ],
    i18n: { title: { fr: "Souffle de l'océan", en: "Ocean breath" } },
    premium_only: false,
  },
  {
    slug: "breath-counted-2min",
    category: "breathing",
    title: "Compter le souffle",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "Inspire — compte 1.", "Inhale — count 1."),
      step(2, "Expire — compte 2.", "Exhale — count 2."),
      step(3, "Continue jusqu'à 10, recommence à 1.", "Continue to 10, restart at 1."),
      step(4, "Si tu perds le compte : reprends à 1.", "If you lose count: restart at 1."),
    ],
    i18n: { title: { fr: "Compter le souffle", en: "Counted breath" } },
    premium_only: false,
  },
  {
    slug: "breath-extended-exhale-2min",
    category: "breathing",
    title: "Expir long apaisant",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["sommeil", "calme"],
    contraindications: [],
    steps: [
      step(1, "Inspire 4 secondes.", "Inhale 4 seconds."),
      step(2, "Expire 8 secondes.", "Exhale 8 seconds."),
      step(3, "L'expir long signale au système nerveux : repos.", "Long exhale signals the nervous system: rest."),
      step(4, "10 cycles environ.", "About 10 cycles."),
    ],
    i18n: { title: { fr: "Expir long apaisant", en: "Calming long exhale" } },
    premium_only: false,
  },
  {
    slug: "breath-three-part-3min",
    category: "breathing",
    title: "Souffle en trois parties",
    duration_seconds: 180,
    intensity: "medium",
    goal_tags: ["calme", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Inspire dans le ventre, puis le diaphragme, puis le haut de la poitrine.", "Inhale into belly, then diaphragm, then upper chest."),
      step(2, "Expire dans l'ordre inverse.", "Exhale in reverse order."),
      step(3, "Lent, sans forcer.", "Slow, no forcing."),
      step(4, "Continue 8-10 cycles.", "Continue 8-10 cycles."),
    ],
    i18n: { title: { fr: "Souffle en trois parties", en: "Three-part breath" } },
    premium_only: false,
  },
  {
    slug: "breath-reset-1min",
    category: "breathing",
    title: "Réinitialisation 1 min",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["calme", "focus"],
    contraindications: [],
    steps: [
      step(1, "Tu peux fermer les yeux.", "You can close your eyes."),
      step(2, "5 respirations lentes, profondes.", "5 slow, deep breaths."),
      step(3, "À chaque expir, relâche les épaules.", "On each exhale, release the shoulders."),
      step(4, "Reviens, plus posé·e.", "Return, more settled."),
    ],
    i18n: { title: { fr: "Réinitialisation 1 min", en: "1 min reset" } },
    premium_only: false,
  },

];
