import type { PracticeSeed } from "./types";

function step(order: number, text_fr: string, text_en: string, duration_seconds?: number) {
  return { order, text_fr, text_en, duration_seconds };
}

export const LEARNING_PRACTICES: PracticeSeed[] = [
  {
    slug: "learn-stoic-control-2min",
    category: "learning",
    title: "Ce qui dépend de toi (stoïcisme)",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus", "calme"],
    contraindications: [],
    steps: [
      step(1, "Liste mentalement 3 choses qui te préoccupent.", "Mentally list 3 things on your mind."),
      step(2, "Pour chacune : dépend de moi ? Pas de moi ?", "For each: depends on me? Not on me?"),
      step(3, "Mets ton énergie sur celles qui dépendent de toi.", "Put energy on those that depend on you."),
      step(4, "Lâche les autres pour cette minute.", "Release the others for this minute."),
    ],
    i18n: { title: { fr: "Ce qui dépend de toi (stoïcisme)", en: "What's in your control (Stoicism)" } },
    premium_only: false,
  },
  {
    slug: "learn-bias-confirmation-2min",
    category: "learning",
    title: "Le biais de confirmation",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "On voit ce qu'on s'attend à voir.", "We see what we expect to see."),
      step(2, "Quel pré-jugement t'a déjà piégé·e ?", "What pre-judgment has tripped you up?"),
      step(3, "Aujourd'hui : essaie de remarquer 1 contre-exemple.", "Today: try to notice 1 counter-example."),
      step(4, "Ralentir = remarquer.", "Slowing down = noticing."),
    ],
    i18n: { title: { fr: "Le biais de confirmation", en: "Confirmation bias" } },
    premium_only: false,
  },
  {
    slug: "learn-attention-residue-1min",
    category: "learning",
    title: "Le résidu d'attention",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "Quand tu changes de tâche, ton attention reste un peu derrière.", "When you switch tasks, attention lingers."),
      step(2, "Une transition consciente coupe le résidu.", "A conscious transition cuts the residue."),
      step(3, "3 respirations entre 2 tâches suffisent.", "3 breaths between tasks is enough."),
      step(4, "Essaie aujourd'hui.", "Try it today."),
    ],
    i18n: { title: { fr: "Le résidu d'attention", en: "Attention residue" } },
    premium_only: false,
  },
  {
    slug: "learn-vagus-nerve-2min",
    category: "learning",
    title: "Le nerf vague (basique)",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["calme"],
    contraindications: [],
    steps: [
      step(1, "Le nerf vague relie le cerveau aux organes.", "The vagus nerve connects brain to organs."),
      step(2, "Un expir long stimule sa branche apaisante.", "A long exhale stimulates its calming branch."),
      step(3, "C'est pourquoi 'expirer plus que tu inspires' calme.", "That's why 'exhale longer than inhale' calms."),
      step(4, "Souvenir-toi : long expir = calme.", "Remember: long exhale = calm."),
    ],
    i18n: { title: { fr: "Le nerf vague (basique)", en: "Vagus nerve (basics)" } },
    premium_only: false,
  },
  {
    slug: "learn-implementation-intent-1min",
    category: "learning",
    title: "Intention d'implémentation",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "'Je veux faire X' échoue souvent.", "'I want to do X' often fails."),
      step(2, "'Quand Y arrive, je fais X' marche mieux.", "'When Y happens, I do X' works better."),
      step(3, "Trouve UN couple Y→X pour aujourd'hui.", "Find ONE Y→X pair for today."),
      step(4, "Note-le mentalement.", "Note it mentally."),
    ],
    i18n: { title: { fr: "Intention d'implémentation", en: "Implementation intention" } },
    premium_only: false,
  },
  {
    slug: "learn-rumi-poem-2min",
    category: "learning",
    title: "Sagesse de Rumi",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "'La blessure est l'endroit où la lumière entre.'", "'The wound is where the light enters.'"),
      step(2, "Pense à une difficulté récente.", "Think of a recent difficulty."),
      step(3, "Quelle lumière a-t-elle laissé passer ?", "What light did it let through?"),
      step(4, "Reste avec cette idée 30s.", "Stay with that idea 30s."),
    ],
    i18n: { title: { fr: "Sagesse de Rumi", en: "Rumi's wisdom" } },
    premium_only: false,
  },
  {
    slug: "learn-flow-state-2min",
    category: "learning",
    title: "Le flow",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "Le flow = défi juste au-dessus de tes capacités.", "Flow = challenge just above your skill."),
      step(2, "Trop facile → ennui. Trop dur → angoisse.", "Too easy → boredom. Too hard → anxiety."),
      step(3, "Sur quoi pourrais-tu trouver ton 'juste' aujourd'hui ?", "Where could you find your 'just right' today?"),
      step(4, "1 micro-décision suffit.", "One micro-decision is enough."),
    ],
    i18n: { title: { fr: "Le flow", en: "Flow state" } },
    premium_only: false,
  },
  {
    slug: "learn-self-talk-2min",
    category: "learning",
    title: "Le dialogue intérieur",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["calme"],
    contraindications: [],
    steps: [
      step(1, "Comment tu te parles change ce que tu vis.", "How you talk to yourself shapes what you live."),
      step(2, "Note une phrase que tu te dis souvent.", "Notice a phrase you tell yourself often."),
      step(3, "Tu la dirais à ton meilleur·e ami·e ?", "Would you say it to your best friend?"),
      step(4, "Si non — adoucis-la pour toi.", "If not — soften it for yourself."),
    ],
    i18n: { title: { fr: "Le dialogue intérieur", en: "Self-talk" } },
    premium_only: false,
  },
  {
    slug: "learn-habit-stack-1min",
    category: "learning",
    title: "Empiler les habitudes",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "Greffe une nouvelle habitude sur une ancienne.", "Stack a new habit onto an old one."),
      step(2, "Ex : après le café → 1 min de respiration.", "Ex: after coffee → 1 min of breath."),
      step(3, "Quel ancrage existe déjà chez toi ?", "What anchor already exists for you?"),
      step(4, "Greffe une micro-action légère.", "Stack a light micro-action."),
    ],
    i18n: { title: { fr: "Empiler les habitudes", en: "Habit stacking" } },
    premium_only: false,
  },
  {
    slug: "learn-impermanence-2min",
    category: "learning",
    title: "L'impermanence",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite", "calme"],
    contraindications: [],
    steps: [
      step(1, "Tout passe — les bons moments comme les durs.", "Everything passes — the good and the hard."),
      step(2, "Ce que tu vis maintenant aussi.", "What you live now too."),
      step(3, "Pas une excuse pour fuir : un rappel pour ne pas s'agripper.", "Not an excuse to flee: a reminder not to cling."),
      step(4, "Reste avec l'idée 30s.", "Stay with the idea 30s."),
    ],
    i18n: { title: { fr: "L'impermanence", en: "Impermanence" } },
    premium_only: false,
  },

];
