import type { PracticeSeed } from "./types";

function step(order: number, text_fr: string, text_en: string, duration_seconds?: number) {
  return { order, text_fr, text_en, duration_seconds };
}

export const MANTRA_PRACTICES: PracticeSeed[] = [
  {
    slug: "mantra-so-hum-2min",
    category: "mantra",
    title: "So Hum",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite", "calme"],
    contraindications: [],
    steps: [
      step(1, "Inspire — silencieusement : 'So'.", "Inhale — silently: 'So'."),
      step(2, "Expire — silencieusement : 'Hum'.", "Exhale — silently: 'Hum'."),
      step(3, "Laisse le rythme s'installer.", "Let the rhythm settle."),
      step(4, "Continue 2 minutes.", "Continue for 2 minutes."),
    ],
    i18n: { title: { fr: "So Hum", en: "So Hum" } },
    premium_only: false,
  },
  {
    slug: "mantra-i-am-here-1min",
    category: "mantra",
    title: "Je suis ici",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["ancrage", "calme"],
    contraindications: [],
    steps: [
      step(1, "Inspire.", "Inhale."),
      step(2, "Expire en pensant : 'Je suis ici.'", "Exhale thinking: 'I am here.'"),
      step(3, "Répète 10 fois.", "Repeat 10 times."),
      step(4, "Sens où tu es vraiment.", "Feel where you really are."),
    ],
    i18n: { title: { fr: "Je suis ici", en: "I am here" } },
    premium_only: false,
  },
  {
    slug: "mantra-hooponopono-3min",
    category: "mantra",
    title: "Ho'oponopono",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["spiritualite", "release"],
    contraindications: [],
    steps: [
      step(1, "Pense à une situation à apaiser.", "Think of a situation to soothe."),
      step(2, "Dis intérieurement : 'Désolé·e.'", "Internally say: 'I'm sorry.'"),
      step(3, "Puis : 'Pardon. Merci. Je t'aime.'", "Then: 'Please forgive me. Thank you. I love you.'"),
      step(4, "Répète, lentement.", "Repeat, slowly."),
    ],
    i18n: { title: { fr: "Ho'oponopono", en: "Ho'oponopono" } },
    premium_only: false,
  },
  {
    slug: "mantra-om-2min",
    category: "mantra",
    title: "Om",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Inspire profondément.", "Inhale deeply."),
      step(2, "Sur l'expir, prononce 'Ooommm' lentement.", "On the exhale, sound 'Ooommm' slowly."),
      step(3, "Sens la vibration dans la poitrine.", "Feel the vibration in the chest."),
      step(4, "10 répétitions.", "10 repetitions."),
    ],
    i18n: { title: { fr: "Om", en: "Om" } },
    premium_only: false,
  },
  {
    slug: "mantra-thank-you-1min",
    category: "mantra",
    title: "Merci",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Inspire.", "Inhale."),
      step(2, "Expire en pensant 'Merci.'", "Exhale thinking 'Thank you.'"),
      step(3, "Pour rien en particulier — ou pour tout.", "For nothing in particular — or for everything."),
      step(4, "10 cycles.", "10 cycles."),
    ],
    i18n: { title: { fr: "Merci", en: "Thank you" } },
    premium_only: false,
  },
  {
    slug: "mantra-i-allow-2min",
    category: "mantra",
    title: "Je m'autorise",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Inspire.", "Inhale."),
      step(2, "Expire : 'Je m'autorise à être là.'", "Exhale: 'I allow myself to be here.'"),
      step(3, "Puis : 'Je m'autorise à ralentir.'", "Then: 'I allow myself to slow down.'"),
      step(4, "Puis : 'Je m'autorise à exister.'", "Then: 'I allow myself to exist.'"),
    ],
    i18n: { title: { fr: "Je m'autorise", en: "I allow myself" } },
    premium_only: false,
  },
  {
    slug: "mantra-let-go-1min",
    category: "mantra",
    title: "Je relâche",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["release", "calme"],
    contraindications: [],
    steps: [
      step(1, "Inspire les épaules vers le haut.", "Inhale shoulders up."),
      step(2, "Expire en disant 'Je relâche.'", "Exhale saying 'I release.'"),
      step(3, "Les épaules redescendent.", "Shoulders drop."),
      step(4, "Répète 5 fois.", "Repeat 5 times."),
    ],
    i18n: { title: { fr: "Je relâche", en: "I release" } },
    premium_only: false,
  },
  {
    slug: "mantra-courage-2min",
    category: "mantra",
    title: "Mantra du courage",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["courage", "energie"],
    contraindications: [],
    steps: [
      step(1, "'Je peux faire ça.'", "'I can do this.'"),
      step(2, "'Une chose à la fois.'", "'One step at a time.'"),
      step(3, "'Je fais déjà beaucoup.'", "'I'm already doing a lot.'"),
      step(4, "Répète celui qui te touche.", "Repeat the one that resonates."),
    ],
    i18n: { title: { fr: "Mantra du courage", en: "Courage mantra" } },
    premium_only: false,
  },
  {
    slug: "mantra-peace-3min",
    category: "mantra",
    title: "Mantra de paix",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["calme", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "'Je suis en paix.'", "'I am at peace.'"),
      step(2, "'Tout est en ordre.'", "'All is well.'"),
      step(3, "'Je n'ai rien à prouver.'", "'I have nothing to prove.'"),
      step(4, "Choisis-en un et reste avec.", "Pick one and stay with it."),
    ],
    i18n: { title: { fr: "Mantra de paix", en: "Peace mantra" } },
    premium_only: false,
  },
  {
    slug: "mantra-abundance-2min",
    category: "mantra",
    title: "Mantra d'abondance",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "'J'ai assez. Je suis assez.'", "'I have enough. I am enough.'"),
      step(2, "'Ce qui est juste pour moi vient à moi.'", "'What is right for me comes to me.'"),
      step(3, "Répète sans forcer la conviction.", "Repeat without forcing belief."),
      step(4, "Laisse les phrases s'imprégner.", "Let the phrases settle."),
    ],
    i18n: { title: { fr: "Mantra d'abondance", en: "Abundance mantra" } },
    premium_only: false,
  },
  {
    slug: "mantra-evening-1min",
    category: "mantra",
    title: "Mantra du soir",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["sommeil", "calme"],
    contraindications: [],
    steps: [
      step(1, "'La journée est terminée.'", "'The day is done.'"),
      step(2, "'Je peux poser les choses.'", "'I can set things down.'"),
      step(3, "'Demain est demain.'", "'Tomorrow is tomorrow.'"),
      step(4, "Souffle long.", "Long exhale."),
    ],
    i18n: { title: { fr: "Mantra du soir", en: "Evening mantra" } },
    premium_only: false,
  },
  {
    slug: "mantra-here-now-30s",
    category: "mantra",
    title: "Ici, maintenant",
    duration_seconds: 30,
    intensity: "gentle",
    goal_tags: ["ancrage", "focus"],
    contraindications: [],
    steps: [
      step(1, "Inspire : 'Ici.'", "Inhale: 'Here.'"),
      step(2, "Expire : 'Maintenant.'", "Exhale: 'Now.'"),
      step(3, "10 cycles.", "10 cycles."),
    ],
    i18n: { title: { fr: "Ici, maintenant", en: "Here, now" } },
    premium_only: false,
  },

];
