import type { PracticeSeed } from "./types";

function step(order: number, text_fr: string, text_en: string, duration_seconds?: number) {
  return { order, text_fr, text_en, duration_seconds };
}

export const MEDITATION_PRACTICES: PracticeSeed[] = [
  {
    slug: "med-body-scan-3min",
    category: "meditation",
    title: "Scan corporel doux",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["calme", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Pose-toi confortablement, ferme les yeux ou baisse le regard.", "Settle comfortably, close or soften your gaze."),
      step(2, "Porte ton attention sur tes pieds, sans rien changer.", "Bring attention to your feet, without changing anything."),
      step(3, "Remonte lentement : jambes, bassin, ventre, poitrine, épaules.", "Slowly travel up: legs, hips, belly, chest, shoulders."),
      step(4, "Termine par le visage et le sommet de la tête.", "Finish at the face and the crown."),
      step(5, "Reviens à l'instant, ouvre les yeux quand tu veux.", "Return to the moment, open eyes when ready."),
    ],
    i18n: { title: { fr: "Scan corporel doux", en: "Gentle body scan" } },
    premium_only: false,
  },
  {
    slug: "med-presence-1min",
    category: "meditation",
    title: "Présence éclair",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["focus", "calme"],
    contraindications: [],
    steps: [
      step(1, "Trois respirations profondes, sans forcer.", "Three deep breaths, without forcing."),
      step(2, "Note un son que tu entends.", "Notice one sound you hear."),
      step(3, "Note une sensation dans ton corps.", "Notice one sensation in your body."),
      step(4, "Tu es ici. C'est tout ce qu'il faut.", "You are here. That's all that's needed."),
    ],
    i18n: { title: { fr: "Présence éclair", en: "Quick presence" } },
    premium_only: false,
  },
  {
    slug: "med-metta-loving-2min",
    category: "meditation",
    title: "Bienveillance partagée",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["calme", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Pense à toi : 'Que je sois en paix.'", "Think of yourself: 'May I be at peace.'"),
      step(2, "Pense à un proche : 'Qu'iel soit en paix.'", "Think of someone close: 'May they be at peace.'"),
      step(3, "Pense à une personne neutre : 'Qu'iel soit en paix.'", "Think of a neutral person: 'May they be at peace.'"),
      step(4, "Pense à toustes : 'Que tout être soit en paix.'", "Think of everyone: 'May all beings be at peace.'"),
    ],
    i18n: { title: { fr: "Bienveillance partagée", en: "Shared loving-kindness" } },
    premium_only: false,
  },
  {
    slug: "med-breath-watch-3min",
    category: "meditation",
    title: "Observer la respiration",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["calme", "focus"],
    contraindications: [],
    steps: [
      step(1, "Laisse ta respiration naturelle, sans la modifier.", "Let your breath be natural, no changes."),
      step(2, "Note l'air qui entre par les narines.", "Notice the air entering through the nostrils."),
      step(3, "Note l'air qui sort.", "Notice the air leaving."),
      step(4, "Si l'esprit part, reviens — sans jugement.", "If the mind drifts, return — no judgment."),
    ],
    i18n: { title: { fr: "Observer la respiration", en: "Watch the breath" } },
    premium_only: false,
  },
  {
    slug: "med-sounds-2min",
    category: "meditation",
    title: "Écoute large",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["calme", "focus"],
    contraindications: [],
    steps: [
      step(1, "Ferme les yeux, laisse les sons venir.", "Close eyes, let sounds come to you."),
      step(2, "N'analyse pas, n'évalue pas.", "Don't analyze, don't judge."),
      step(3, "Note simplement : proche / lointain.", "Just notice: near / far."),
      step(4, "Reviens à toi quand tu es prêt·e.", "Return when ready."),
    ],
    i18n: { title: { fr: "Écoute large", en: "Open listening" } },
    premium_only: false,
  },
  {
    slug: "med-anchor-feet-1min",
    category: "meditation",
    title: "Ancrage par les pieds",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["ancrage", "calme"],
    contraindications: [],
    steps: [
      step(1, "Pose les pieds bien à plat.", "Place feet flat on the floor."),
      step(2, "Sens chaque point de contact.", "Feel each point of contact."),
      step(3, "Imagine des racines qui descendent.", "Imagine roots growing down."),
      step(4, "Tu es là. Tu es soutenu·e.", "You are here. You are supported."),
    ],
    i18n: { title: { fr: "Ancrage par les pieds", en: "Foot grounding" } },
    premium_only: false,
  },
  {
    slug: "med-gratitude-3min",
    category: "meditation",
    title: "Méditation gratitude",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["spiritualite", "calme"],
    contraindications: [],
    steps: [
      step(1, "Pense à 3 choses simples du jour.", "Think of 3 simple things from today."),
      step(2, "Pour chacune, sens dans le corps ce qu'elle réveille.", "For each, feel what it awakens in your body."),
      step(3, "Reste avec cette chaleur 30 secondes.", "Stay with that warmth for 30 seconds."),
      step(4, "Reviens, le sourire intérieur intact.", "Return, the inner smile intact."),
    ],
    i18n: { title: { fr: "Méditation gratitude", en: "Gratitude meditation" } },
    premium_only: false,
  },
  {
    slug: "med-letting-go-5min",
    category: "meditation",
    title: "Laisser passer",
    duration_seconds: 300,
    intensity: "medium",
    goal_tags: ["calme", "release"],
    contraindications: [],
    steps: [
      step(1, "Identifie une pensée qui revient en boucle.", "Identify a recurring thought."),
      step(2, "Imagine-la comme un nuage qui passe.", "Picture it as a passing cloud."),
      step(3, "Tu peux la voir, tu n'es pas obligé·e de la suivre.", "You can see it, you don't have to follow it."),
      step(4, "Reviens au souffle, calmement.", "Return to the breath, calmly."),
    ],
    i18n: { title: { fr: "Laisser passer", en: "Let it pass" } },
    premium_only: false,
  },
  {
    slug: "med-loving-self-2min",
    category: "meditation",
    title: "Auto-bienveillance",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["calme", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Pose une main sur le cœur.", "Place a hand on your heart."),
      step(2, "Dis-toi : 'Je fais de mon mieux.'", "Tell yourself: 'I'm doing my best.'"),
      step(3, "Sens la chaleur de ta main.", "Feel the warmth of your hand."),
      step(4, "Reste 30 secondes dans cette douceur.", "Stay 30 seconds in this softness."),
    ],
    i18n: { title: { fr: "Auto-bienveillance", en: "Self-kindness" } },
    premium_only: false,
  },
  {
    slug: "med-noting-thoughts-3min",
    category: "meditation",
    title: "Étiqueter les pensées",
    duration_seconds: 180,
    intensity: "medium",
    goal_tags: ["focus", "calme"],
    contraindications: [],
    steps: [
      step(1, "Quand une pensée arrive, dis 'pensée' silencieusement.", "When a thought arrives, silently say 'thinking'."),
      step(2, "Une émotion ? 'sentir'.", "An emotion? 'feeling'."),
      step(3, "Un son ? 'entendre'.", "A sound? 'hearing'."),
      step(4, "Reviens à la respiration entre les notes.", "Return to the breath between notes."),
    ],
    i18n: { title: { fr: "Étiqueter les pensées", en: "Noting thoughts" } },
    premium_only: false,
  },
  {
    slug: "med-evening-arrival-2min",
    category: "meditation",
    title: "Arrivée du soir",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["sommeil", "calme"],
    contraindications: [],
    steps: [
      step(1, "Prends conscience que la journée se termine.", "Notice the day is ending."),
      step(2, "Identifie un moment marquant — sans le juger.", "Identify a moment that stood out — without judging."),
      step(3, "Remercie ton corps pour ce qu'il a porté.", "Thank your body for what it carried."),
      step(4, "Pose les yeux sur un point neutre.", "Rest your gaze on a neutral point."),
    ],
    i18n: { title: { fr: "Arrivée du soir", en: "Evening arrival" } },
    premium_only: false,
  },
  {
    slug: "med-deep-stillness-7min",
    category: "meditation",
    title: "Silence profond",
    duration_seconds: 420,
    intensity: "medium",
    goal_tags: ["spiritualite", "calme"],
    contraindications: [],
    steps: [
      step(1, "Position stable, dos droit, mains posées.", "Stable position, straight back, hands resting."),
      step(2, "5 respirations conscientes pour entrer.", "5 conscious breaths to enter."),
      step(3, "Laisse l'attention reposer sur l'espace entre les pensées.", "Let attention rest in the space between thoughts."),
      step(4, "Si l'esprit part, reviens — encore et encore.", "If mind drifts, return — again and again."),
      step(5, "Sors lentement, sans précipitation.", "Exit slowly, no rush."),
    ],
    i18n: { title: { fr: "Silence profond", en: "Deep stillness" } },
    premium_only: true,
  },
];
