import type { PracticeSeed } from "./types";

function step(order: number, text_fr: string, text_en: string, duration_seconds?: number) {
  return { order, text_fr, text_en, duration_seconds };
}

export const MOVEMENT_PRACTICES: PracticeSeed[] = [
  {
    slug: "move-shoulders-roll-1min",
    category: "movement",
    title: "Rotation des épaules",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["release", "calme"],
    contraindications: ["epaule_blessee"],
    steps: [
      step(1, "Lève les épaules vers les oreilles.", "Lift shoulders toward ears."),
      step(2, "Roule en arrière, lentement.", "Roll backward, slowly."),
      step(3, "5 cercles arrière, 5 cercles avant.", "5 backward circles, 5 forward."),
      step(4, "Termine immobile, conscient·e.", "End still, aware."),
    ],
    i18n: { title: { fr: "Rotation des épaules", en: "Shoulder rolls" } },
    premium_only: false,
  },
  {
    slug: "move-neck-stretch-2min",
    category: "movement",
    title: "Étirements de la nuque",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["release"],
    contraindications: ["cervicales_blessees"],
    steps: [
      step(1, "Oreille vers épaule droite, 30s.", "Right ear to shoulder, 30s."),
      step(2, "Retour, oreille vers épaule gauche, 30s.", "Return, left ear to shoulder, 30s."),
      step(3, "Menton vers poitrine, 30s.", "Chin to chest, 30s."),
      step(4, "Retour neutre, respire.", "Return neutral, breathe."),
    ],
    i18n: { title: { fr: "Étirements de la nuque", en: "Neck stretches" } },
    premium_only: false,
  },
  {
    slug: "move-cat-cow-2min",
    category: "movement",
    title: "Chat-vache",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["release", "ancrage"],
    contraindications: ["dos_blessure_aigue"],
    steps: [
      step(1, "À quatre pattes, dos neutre.", "On all fours, neutral back."),
      step(2, "Inspire : creuse le dos, regarde devant.", "Inhale: arch back, look forward."),
      step(3, "Expire : arrondis le dos, menton rentré.", "Exhale: round back, chin tucked."),
      step(4, "10 cycles lents.", "10 slow cycles."),
    ],
    i18n: { title: { fr: "Chat-vache", en: "Cat-cow" } },
    premium_only: false,
  },
  {
    slug: "move-side-stretch-1min",
    category: "movement",
    title: "Étirement latéral debout",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["release", "energie"],
    contraindications: [],
    steps: [
      step(1, "Debout, bras gauche au-dessus.", "Standing, left arm overhead."),
      step(2, "Penche-toi à droite, 20s.", "Bend right, 20s."),
      step(3, "Change de côté.", "Switch sides."),
      step(4, "Respire largement.", "Breathe widely."),
    ],
    i18n: { title: { fr: "Étirement latéral debout", en: "Standing side stretch" } },
    premium_only: false,
  },
  {
    slug: "move-mindful-walk-3min",
    category: "movement",
    title: "Marche consciente",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["ancrage", "focus"],
    contraindications: [],
    steps: [
      step(1, "Marche lentement, talon-pointe.", "Walk slowly, heel-toe."),
      step(2, "Sens chaque pas, sans vitesse.", "Feel each step, no rush."),
      step(3, "Respiration synchronisée 4 pas / 4 pas.", "Breath synced 4 steps / 4 steps."),
      step(4, "Pose-toi en fin.", "Settle at the end."),
    ],
    i18n: { title: { fr: "Marche consciente", en: "Mindful walk" } },
    premium_only: false,
  },
  {
    slug: "move-shake-30s",
    category: "movement",
    title: "Secouer le stress",
    duration_seconds: 30,
    intensity: "medium",
    goal_tags: ["release", "energie"],
    contraindications: ["dos_blessure_aigue"],
    steps: [
      step(1, "Debout, secoue les bras et les jambes.", "Standing, shake arms and legs."),
      step(2, "Tout le corps tremble doucement.", "Whole body shakes lightly."),
      step(3, "Imagine que tu déposes ce qui pèse.", "Imagine setting down what weighs."),
      step(4, "Stop. Respire.", "Stop. Breathe."),
    ],
    i18n: { title: { fr: "Secouer le stress", en: "Stress shake-out" } },
    premium_only: false,
  },
  {
    slug: "move-sun-greeting-3min",
    category: "movement",
    title: "Salutation au matin",
    duration_seconds: 180,
    intensity: "medium",
    goal_tags: ["energie", "ancrage"],
    contraindications: ["genou_blesse"],
    steps: [
      step(1, "Debout, mains jointes au cœur.", "Standing, hands at heart."),
      step(2, "Bras vers le ciel, légère extension arrière.", "Arms up, slight backbend."),
      step(3, "Flexion avant, mains vers le sol.", "Forward fold, hands toward floor."),
      step(4, "Remonte, retour mains au cœur.", "Rise, hands back to heart."),
      step(5, "Répète 3 fois.", "Repeat 3 times."),
    ],
    i18n: { title: { fr: "Salutation au matin", en: "Morning greeting" } },
    premium_only: false,
  },
  {
    slug: "move-figure-eight-1min",
    category: "movement",
    title: "Bassin en huit",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["release", "energie"],
    contraindications: [],
    steps: [
      step(1, "Debout, genoux légèrement fléchis.", "Standing, knees slightly bent."),
      step(2, "Dessine un huit horizontal avec le bassin.", "Draw a horizontal 8 with the hips."),
      step(3, "Sens-le partout dans le ventre.", "Feel it everywhere in the belly."),
      step(4, "Inverse le sens à mi-temps.", "Reverse direction halfway."),
    ],
    i18n: { title: { fr: "Bassin en huit", en: "Hip figure-8" } },
    premium_only: false,
  },
  {
    slug: "move-tension-release-2min",
    category: "movement",
    title: "Contracter-relâcher",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["release", "calme"],
    contraindications: [],
    steps: [
      step(1, "Contracte les pieds 5s, relâche.", "Tense feet 5s, release."),
      step(2, "Mollets, cuisses, fessiers — chacun 5s.", "Calves, thighs, glutes — each 5s."),
      step(3, "Ventre, mains, bras, visage.", "Belly, hands, arms, face."),
      step(4, "Termine, tout le corps lâche.", "End, whole body releases."),
    ],
    i18n: { title: { fr: "Contracter-relâcher", en: "Tense and release" } },
    premium_only: false,
  },
  {
    slug: "move-spinal-twist-2min",
    category: "movement",
    title: "Torsion assise",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["release"],
    contraindications: ["dos_blessure_aigue", "grossesse_avis_medecin"],
    steps: [
      step(1, "Assis·e, jambes croisées.", "Seated, legs crossed."),
      step(2, "Main droite sur genou gauche.", "Right hand on left knee."),
      step(3, "Tourne doucement à gauche, 30s.", "Slowly twist left, 30s."),
      step(4, "Change de côté.", "Switch sides."),
    ],
    i18n: { title: { fr: "Torsion assise", en: "Seated twist" } },
    premium_only: false,
  },
  {
    slug: "move-foot-massage-1min",
    category: "movement",
    title: "Auto-massage des pieds",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["ancrage", "calme"],
    contraindications: [],
    steps: [
      step(1, "Croise une cheville sur ton genou.", "Cross one ankle over your knee."),
      step(2, "Masse la voûte plantaire avec les pouces.", "Massage the arch with your thumbs."),
      step(3, "Insiste où ça serre.", "Linger where it's tight."),
      step(4, "Change de pied.", "Switch feet."),
    ],
    i18n: { title: { fr: "Auto-massage des pieds", en: "Foot self-massage" } },
    premium_only: false,
  },
  {
    slug: "move-childs-pose-2min",
    category: "movement",
    title: "Posture de l'enfant",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["calme", "release"],
    contraindications: ["genou_blesse"],
    steps: [
      step(1, "À genoux, gros orteils joints.", "On knees, big toes touching."),
      step(2, "Assieds-toi sur tes talons.", "Sit on your heels."),
      step(3, "Penche-toi en avant, front au sol.", "Fold forward, forehead to floor."),
      step(4, "Bras devant ou le long du corps. Respire.", "Arms forward or by sides. Breathe."),
    ],
    i18n: { title: { fr: "Posture de l'enfant", en: "Child's pose" } },
    premium_only: false,
  },

];
