import type { PracticeSeed } from "./types";

function step(order: number, text_fr: string, text_en: string, duration_seconds?: number) {
  return { order, text_fr, text_en, duration_seconds };
}

export const MUDRA_PRACTICES: PracticeSeed[] = [
  {
    slug: "mudra-gyan-3min",
    category: "mudra",
    title: "Gyan mudra",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["focus", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Joins le pouce et l'index, autres doigts détendus.", "Join thumb and index, other fingers relaxed."),
      step(2, "Pose les mains sur les genoux, paumes vers le ciel.", "Rest hands on knees, palms up."),
      step(3, "Respire calmement.", "Breathe calmly."),
      step(4, "Reste 3 minutes.", "Hold for 3 minutes."),
    ],
    i18n: { title: { fr: "Gyan mudra", en: "Gyan mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-anjali-1min",
    category: "mudra",
    title: "Anjali (mains jointes)",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["spiritualite", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Joins les paumes au cœur.", "Join palms at the heart."),
      step(2, "Légère pression entre les paumes.", "Slight pressure between palms."),
      step(3, "Respire dans cet espace.", "Breathe into that space."),
      step(4, "1 minute.", "1 minute."),
    ],
    i18n: { title: { fr: "Anjali (mains jointes)", en: "Anjali (joined hands)" } },
    premium_only: false,
  },
  {
    slug: "mudra-prana-2min",
    category: "mudra",
    title: "Prana mudra",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["energie"],
    contraindications: [],
    steps: [
      step(1, "Pouce + auriculaire + annulaire.", "Thumb + pinky + ring finger."),
      step(2, "Index et majeur tendus.", "Index and middle extended."),
      step(3, "Mains posées, paumes vers le ciel.", "Hands resting, palms up."),
      step(4, "Respire 2 minutes.", "Breathe for 2 minutes."),
    ],
    i18n: { title: { fr: "Prana mudra", en: "Prana mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-shuni-2min",
    category: "mudra",
    title: "Shuni mudra",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus", "calme"],
    contraindications: [],
    steps: [
      step(1, "Joins le pouce et le majeur.", "Join thumb and middle finger."),
      step(2, "Détends les autres doigts.", "Relax the other fingers."),
      step(3, "Mains sur genoux.", "Hands on knees."),
      step(4, "2 minutes de respiration calme.", "2 minutes of calm breath."),
    ],
    i18n: { title: { fr: "Shuni mudra", en: "Shuni mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-surya-2min",
    category: "mudra",
    title: "Surya mudra",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["energie"],
    contraindications: [],
    steps: [
      step(1, "Pli l'annulaire vers la base du pouce.", "Fold ring finger to thumb base."),
      step(2, "Pouce sur l'annulaire, autres doigts tendus.", "Thumb over ring, other fingers extended."),
      step(3, "Mains sur les cuisses.", "Hands on thighs."),
      step(4, "2 minutes.", "2 minutes."),
    ],
    i18n: { title: { fr: "Surya mudra", en: "Surya mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-apana-3min",
    category: "mudra",
    title: "Apana mudra",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["release", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Pouce + majeur + annulaire ensemble.", "Thumb + middle + ring together."),
      step(2, "Index et auriculaire détendus.", "Index and pinky relaxed."),
      step(3, "Paumes vers le ciel.", "Palms up."),
      step(4, "3 minutes de respiration ventrale.", "3 minutes of belly breath."),
    ],
    i18n: { title: { fr: "Apana mudra", en: "Apana mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-heart-opening-1min",
    category: "mudra",
    title: "Mudra du cœur ouvert",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["spiritualite", "release"],
    contraindications: [],
    steps: [
      step(1, "Mains posées sur le cœur, l'une sur l'autre.", "Hands on the heart, one on top of the other."),
      step(2, "Sens la chaleur sous tes paumes.", "Feel the warmth under your palms."),
      step(3, "Respire dans cet espace.", "Breathe into that space."),
      step(4, "1 minute.", "1 minute."),
    ],
    i18n: { title: { fr: "Mudra du cœur ouvert", en: "Open heart mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-grounding-2min",
    category: "mudra",
    title: "Mudra d'ancrage",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["ancrage"],
    contraindications: [],
    steps: [
      step(1, "Paumes vers le sol sur les cuisses.", "Palms down on thighs."),
      step(2, "Imagine que ton poids descend.", "Imagine your weight sinking."),
      step(3, "Respire lentement.", "Breathe slowly."),
      step(4, "2 minutes.", "2 minutes."),
    ],
    i18n: { title: { fr: "Mudra d'ancrage", en: "Grounding mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-receiving-1min",
    category: "mudra",
    title: "Mudra de réception",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Paumes vers le ciel sur les cuisses.", "Palms up on thighs."),
      step(2, "Imagine que tu reçois — sans rien forcer.", "Imagine you're receiving — no forcing."),
      step(3, "Respire calmement.", "Breathe calmly."),
      step(4, "1 minute.", "1 minute."),
    ],
    i18n: { title: { fr: "Mudra de réception", en: "Receiving mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-balance-3min",
    category: "mudra",
    title: "Mudra d'équilibre",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["calme", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Une paume vers le ciel, l'autre vers le sol.", "One palm up, one palm down."),
      step(2, "Inverse à mi-temps.", "Switch halfway through."),
      step(3, "Respire en cohérence cardiaque.", "Breathe in heart coherence."),
      step(4, "Total 3 minutes.", "Total 3 minutes."),
    ],
    i18n: { title: { fr: "Mudra d'équilibre", en: "Balance mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-fear-release-2min",
    category: "mudra",
    title: "Mudra anti-peur",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["release", "courage"],
    contraindications: [],
    steps: [
      step(1, "Index et majeur droits, autres doigts repliés.", "Index and middle straight, others folded."),
      step(2, "Main droite levée à hauteur d'épaule.", "Right hand at shoulder height."),
      step(3, "Respire calmement.", "Breathe calmly."),
      step(4, "2 minutes.", "2 minutes."),
    ],
    i18n: { title: { fr: "Mudra anti-peur", en: "Fear-release mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-clarity-2min",
    category: "mudra",
    title: "Mudra de clarté",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "Pouce + index + majeur ensemble.", "Thumb + index + middle together."),
      step(2, "Annulaire et auriculaire tendus.", "Ring and pinky extended."),
      step(3, "Mains sur les cuisses.", "Hands on thighs."),
      step(4, "2 minutes.", "2 minutes."),
    ],
    i18n: { title: { fr: "Mudra de clarté", en: "Clarity mudra" } },
    premium_only: false,
  },

];
