import type { PracticeSeed } from "./types";

function step(order: number, text_fr: string, text_en: string, duration_seconds?: number) {
  return { order, text_fr, text_en, duration_seconds };
}

export const REPROGRAMMING_PRACTICES: PracticeSeed[] = [
  {
    slug: "reprog-confidence-3min",
    category: "reprogramming",
    title: "Affirmations confiance",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["courage", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Inspire profondément.", "Inhale deeply."),
      step(2, "'Je peux compter sur moi.'", "'I can count on myself.'"),
      step(3, "'J'apprends à chaque pas.'", "'I learn with each step.'"),
      step(4, "'Je n'ai rien à prouver.'", "'I have nothing to prove.'"),
      step(5, "Répète celle qui résonne.", "Repeat the one that resonates."),
    ],
    i18n: { title: { fr: "Affirmations confiance", en: "Confidence affirmations" } },
    premium_only: false,
  },
  {
    slug: "reprog-abundance-3min",
    category: "reprogramming",
    title: "Visualisation abondance",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Ferme les yeux.", "Close your eyes."),
      step(2, "Imagine un lieu où tu te sens 'assez'.", "Picture a place where you feel 'enough'."),
      step(3, "Note : couleurs, sons, odeurs, sensations.", "Notice: colors, sounds, smells, sensations."),
      step(4, "Reste 1 minute. Reviens.", "Stay 1 minute. Return."),
    ],
    i18n: { title: { fr: "Visualisation abondance", en: "Abundance visualization" } },
    premium_only: false,
  },
  {
    slug: "reprog-evening-anchor-2min",
    category: "reprogramming",
    title: "Ancrage du soir",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["sommeil"],
    contraindications: [],
    steps: [
      step(1, "Pose une main sur le ventre, l'autre sur le cœur.", "One hand on belly, one on heart."),
      step(2, "'Ma journée est terminée.'", "'My day is done.'"),
      step(3, "'Je peux poser tout ce que j'ai porté.'", "'I can set down what I carried.'"),
      step(4, "'Demain est demain.'", "'Tomorrow is tomorrow.'"),
    ],
    i18n: { title: { fr: "Ancrage du soir", en: "Evening anchor" } },
    premium_only: false,
  },
  {
    slug: "reprog-morning-intent-1min",
    category: "reprogramming",
    title: "Intention du matin",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["focus", "energie"],
    contraindications: [],
    steps: [
      step(1, "Une seule intention pour aujourd'hui.", "One intention for today."),
      step(2, "Pas un objectif — un état d'esprit.", "Not a goal — a mindset."),
      step(3, "Ex : 'présent·e', 'patient·e', 'curieux·se'.", "Ex: 'present', 'patient', 'curious'."),
      step(4, "Répète-la 3 fois.", "Repeat it 3 times."),
    ],
    i18n: { title: { fr: "Intention du matin", en: "Morning intention" } },
    premium_only: false,
  },
  {
    slug: "reprog-self-worth-3min",
    category: "reprogramming",
    title: "Affirmations valeur propre",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "'Je vaux indépendamment de ce que je produis.'", "'I'm worthy regardless of what I produce.'"),
      step(2, "'Je suis assez, tel·le que je suis.'", "'I am enough, as I am.'"),
      step(3, "'Je peux exister sans me justifier.'", "'I can exist without justifying.'"),
      step(4, "Reste avec celle qui pique.", "Stay with the one that stings."),
    ],
    i18n: { title: { fr: "Affirmations valeur propre", en: "Self-worth affirmations" } },
    premium_only: false,
  },
  {
    slug: "reprog-future-self-5min",
    category: "reprogramming",
    title: "Lettre du futur",
    duration_seconds: 300,
    intensity: "medium",
    goal_tags: ["courage", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Imagine ton futur 'toi' dans 1 an, apaisé·e.", "Picture your future self in 1 year, at peace."),
      step(2, "Que te dirait-iel ?", "What would they tell you?"),
      step(3, "Quelle phrase courte choisirait-iel ?", "What short phrase would they choose?"),
      step(4, "Note-la mentalement.", "Note it mentally."),
      step(5, "Garde-la pour aujourd'hui.", "Keep it for today."),
    ],
    i18n: { title: { fr: "Lettre du futur", en: "Letter from the future" } },
    premium_only: false,
  },
  {
    slug: "reprog-release-control-2min",
    category: "reprogramming",
    title: "Lâcher le contrôle",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["release", "calme"],
    contraindications: [],
    steps: [
      step(1, "Liste mentalement 1 chose hors de ton contrôle.", "List 1 thing out of your control."),
      step(2, "Imagine-la dans une boîte.", "Imagine it in a box."),
      step(3, "Pose la boîte à côté de toi.", "Set the box beside you."),
      step(4, "'Pour cet instant, je n'ai pas à la porter.'", "'For now, I don't have to carry it.'"),
    ],
    i18n: { title: { fr: "Lâcher le contrôle", en: "Release control" } },
    premium_only: false,
  },
  {
    slug: "reprog-forgiveness-3min",
    category: "reprogramming",
    title: "Pardon doux",
    duration_seconds: 180,
    intensity: "medium",
    goal_tags: ["release", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Pense à toi, le·la 'toi' d'hier.", "Think of yesterday's you."),
      step(2, "'Tu as fait avec ce que tu avais.'", "'You did with what you had.'"),
      step(3, "'Je peux te pardonner — un peu, pas tout.'", "'I can forgive you — a little, not all.'"),
      step(4, "Le pardon est un chemin, pas un événement.", "Forgiveness is a path, not an event."),
    ],
    i18n: { title: { fr: "Pardon doux", en: "Soft forgiveness" } },
    premium_only: false,
  },
  {
    slug: "reprog-body-appreciation-2min",
    category: "reprogramming",
    title: "Reconnaissance au corps",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite", "calme"],
    contraindications: [],
    steps: [
      step(1, "Pose la main sur ton ventre.", "Place hand on your belly."),
      step(2, "'Merci de me digérer ce que je vis.'", "'Thank you for digesting what I live.'"),
      step(3, "Mains sur le cœur. 'Merci de battre.'", "Hands on heart. 'Thank you for beating.'"),
      step(4, "Mains sur la tête. 'Merci de penser.'", "Hands on head. 'Thank you for thinking.'"),
    ],
    i18n: { title: { fr: "Reconnaissance au corps", en: "Body appreciation" } },
    premium_only: false,
  },
  {
    slug: "reprog-safe-place-3min",
    category: "reprogramming",
    title: "Mon lieu refuge",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["calme", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Imagine un lieu où tu te sens parfaitement à l'aise.", "Picture a place where you feel completely at ease."),
      step(2, "Réel ou inventé — peu importe.", "Real or imagined — doesn't matter."),
      step(3, "Note 3 détails sensoriels.", "Notice 3 sensory details."),
      step(4, "'Ce lieu existe en moi. J'y reviens quand je veux.'", "'This place exists in me. I return when I want.'"),
    ],
    i18n: { title: { fr: "Mon lieu refuge", en: "My safe place" } },
    premium_only: false,
  },
];
