#!/usr/bin/env -S npx tsx
/**
 * Idempotent seed: catalogue de ~80 pratiques KAÏA — 7 catégories.
 *
 * - Upsert par `slug` (re-run sans duplication).
 * - Contenu réel (FR base + EN base i18n). Locales additionnelles ajoutées en P9.
 * - Vérifie le count à la fin.
 *
 * Usage:
 *   npx tsx scripts/seed-practices.ts
 */
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SERVICE_KEY) {
  throw new Error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local");
}

const supabase = createClient(SUPABASE_URL, SERVICE_KEY, {
  db: { schema: "kaia" },
  auth: { persistSession: false },
});

type Category = "meditation" | "breathing" | "mantra" | "mudra" | "movement" | "learning" | "reprogramming";

interface PracticeSeed {
  slug: string;
  category: Category;
  title: string;
  duration_seconds: number;
  intensity: "gentle" | "medium" | "strong";
  goal_tags: string[];
  contraindications: string[];
  steps: Array<{ order: number; text_fr: string; text_en: string; duration_seconds?: number }>;
  i18n: {
    title: { fr: string; en: string };
    description?: { fr: string; en: string };
  };
  premium_only: boolean;
}

function step(order: number, text_fr: string, text_en: string, duration_seconds?: number) {
  return { order, text_fr, text_en, duration_seconds };
}

const PRACTICES: PracticeSeed[] = [
  // ── MÉDITATION ─────────────────────────────────────────────────────────────
  {
    slug: "med-body-scan-3min",
    category: "meditation",
    title: "Scan corporel doux",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["calme", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Pose-toi confortablement, ferme les yeux ou baisse le regard.", "Settle comfortably, close or soften your gaze."),
      step(2, "Porte ton attention sur tes pieds, sans rien changer.", "Bring attention to your feet, without changing anything."),
      step(3, "Remonte lentement : jambes, bassin, ventre, poitrine, épaules.", "Slowly travel up: legs, hips, belly, chest, shoulders."),
      step(4, "Termine par le visage et le sommet de la tête.", "Finish at the face and the crown."),
      step(5, "Reviens à l'instant, ouvre les yeux quand tu veux.", "Return to the moment, open eyes when ready."),
    ],
    i18n: { title: { fr: "Scan corporel doux", en: "Gentle body scan" } },
    premium_only: false,
  },
  {
    slug: "med-presence-1min",
    category: "meditation",
    title: "Présence éclair",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["focus", "calme"],
    contraindications: [],
    steps: [
      step(1, "Trois respirations profondes, sans forcer.", "Three deep breaths, without forcing."),
      step(2, "Note un son que tu entends.", "Notice one sound you hear."),
      step(3, "Note une sensation dans ton corps.", "Notice one sensation in your body."),
      step(4, "Tu es ici. C'est tout ce qu'il faut.", "You are here. That's all that's needed."),
    ],
    i18n: { title: { fr: "Présence éclair", en: "Quick presence" } },
    premium_only: false,
  },
  {
    slug: "med-metta-loving-2min",
    category: "meditation",
    title: "Bienveillance partagée",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["calme", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Pense à toi : 'Que je sois en paix.'", "Think of yourself: 'May I be at peace.'"),
      step(2, "Pense à un proche : 'Qu'iel soit en paix.'", "Think of someone close: 'May they be at peace.'"),
      step(3, "Pense à une personne neutre : 'Qu'iel soit en paix.'", "Think of a neutral person: 'May they be at peace.'"),
      step(4, "Pense à toustes : 'Que tout être soit en paix.'", "Think of everyone: 'May all beings be at peace.'"),
    ],
    i18n: { title: { fr: "Bienveillance partagée", en: "Shared loving-kindness" } },
    premium_only: false,
  },
  {
    slug: "med-breath-watch-3min",
    category: "meditation",
    title: "Observer la respiration",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["calme", "focus"],
    contraindications: [],
    steps: [
      step(1, "Laisse ta respiration naturelle, sans la modifier.", "Let your breath be natural, no changes."),
      step(2, "Note l'air qui entre par les narines.", "Notice the air entering through the nostrils."),
      step(3, "Note l'air qui sort.", "Notice the air leaving."),
      step(4, "Si l'esprit part, reviens — sans jugement.", "If the mind drifts, return — no judgment."),
    ],
    i18n: { title: { fr: "Observer la respiration", en: "Watch the breath" } },
    premium_only: false,
  },
  {
    slug: "med-sounds-2min",
    category: "meditation",
    title: "Écoute large",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["calme", "focus"],
    contraindications: [],
    steps: [
      step(1, "Ferme les yeux, laisse les sons venir.", "Close eyes, let sounds come to you."),
      step(2, "N'analyse pas, n'évalue pas.", "Don't analyze, don't judge."),
      step(3, "Note simplement : proche / lointain.", "Just notice: near / far."),
      step(4, "Reviens à toi quand tu es prêt·e.", "Return when ready."),
    ],
    i18n: { title: { fr: "Écoute large", en: "Open listening" } },
    premium_only: false,
  },
  {
    slug: "med-anchor-feet-1min",
    category: "meditation",
    title: "Ancrage par les pieds",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["ancrage", "calme"],
    contraindications: [],
    steps: [
      step(1, "Pose les pieds bien à plat.", "Place feet flat on the floor."),
      step(2, "Sens chaque point de contact.", "Feel each point of contact."),
      step(3, "Imagine des racines qui descendent.", "Imagine roots growing down."),
      step(4, "Tu es là. Tu es soutenu·e.", "You are here. You are supported."),
    ],
    i18n: { title: { fr: "Ancrage par les pieds", en: "Foot grounding" } },
    premium_only: false,
  },
  {
    slug: "med-gratitude-3min",
    category: "meditation",
    title: "Méditation gratitude",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["spiritualite", "calme"],
    contraindications: [],
    steps: [
      step(1, "Pense à 3 choses simples du jour.", "Think of 3 simple things from today."),
      step(2, "Pour chacune, sens dans le corps ce qu'elle réveille.", "For each, feel what it awakens in your body."),
      step(3, "Reste avec cette chaleur 30 secondes.", "Stay with that warmth for 30 seconds."),
      step(4, "Reviens, le sourire intérieur intact.", "Return, the inner smile intact."),
    ],
    i18n: { title: { fr: "Méditation gratitude", en: "Gratitude meditation" } },
    premium_only: false,
  },
  {
    slug: "med-letting-go-5min",
    category: "meditation",
    title: "Laisser passer",
    duration_seconds: 300,
    intensity: "medium",
    goal_tags: ["calme", "release"],
    contraindications: [],
    steps: [
      step(1, "Identifie une pensée qui revient en boucle.", "Identify a recurring thought."),
      step(2, "Imagine-la comme un nuage qui passe.", "Picture it as a passing cloud."),
      step(3, "Tu peux la voir, tu n'es pas obligé·e de la suivre.", "You can see it, you don't have to follow it."),
      step(4, "Reviens au souffle, calmement.", "Return to the breath, calmly."),
    ],
    i18n: { title: { fr: "Laisser passer", en: "Let it pass" } },
    premium_only: false,
  },
  {
    slug: "med-loving-self-2min",
    category: "meditation",
    title: "Auto-bienveillance",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["calme", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Pose une main sur le cœur.", "Place a hand on your heart."),
      step(2, "Dis-toi : 'Je fais de mon mieux.'", "Tell yourself: 'I'm doing my best.'"),
      step(3, "Sens la chaleur de ta main.", "Feel the warmth of your hand."),
      step(4, "Reste 30 secondes dans cette douceur.", "Stay 30 seconds in this softness."),
    ],
    i18n: { title: { fr: "Auto-bienveillance", en: "Self-kindness" } },
    premium_only: false,
  },
  {
    slug: "med-noting-thoughts-3min",
    category: "meditation",
    title: "Étiqueter les pensées",
    duration_seconds: 180,
    intensity: "medium",
    goal_tags: ["focus", "calme"],
    contraindications: [],
    steps: [
      step(1, "Quand une pensée arrive, dis 'pensée' silencieusement.", "When a thought arrives, silently say 'thinking'."),
      step(2, "Une émotion ? 'sentir'.", "An emotion? 'feeling'."),
      step(3, "Un son ? 'entendre'.", "A sound? 'hearing'."),
      step(4, "Reviens à la respiration entre les notes.", "Return to the breath between notes."),
    ],
    i18n: { title: { fr: "Étiqueter les pensées", en: "Noting thoughts" } },
    premium_only: false,
  },
  {
    slug: "med-evening-arrival-2min",
    category: "meditation",
    title: "Arrivée du soir",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["sommeil", "calme"],
    contraindications: [],
    steps: [
      step(1, "Prends conscience que la journée se termine.", "Notice the day is ending."),
      step(2, "Identifie un moment marquant — sans le juger.", "Identify a moment that stood out — without judging."),
      step(3, "Remercie ton corps pour ce qu'il a porté.", "Thank your body for what it carried."),
      step(4, "Pose les yeux sur un point neutre.", "Rest your gaze on a neutral point."),
    ],
    i18n: { title: { fr: "Arrivée du soir", en: "Evening arrival" } },
    premium_only: false,
  },
  {
    slug: "med-deep-stillness-7min",
    category: "meditation",
    title: "Silence profond",
    duration_seconds: 420,
    intensity: "medium",
    goal_tags: ["spiritualite", "calme"],
    contraindications: [],
    steps: [
      step(1, "Position stable, dos droit, mains posées.", "Stable position, straight back, hands resting."),
      step(2, "5 respirations conscientes pour entrer.", "5 conscious breaths to enter."),
      step(3, "Laisse l'attention reposer sur l'espace entre les pensées.", "Let attention rest in the space between thoughts."),
      step(4, "Si l'esprit part, reviens — encore et encore.", "If mind drifts, return — again and again."),
      step(5, "Sors lentement, sans précipitation.", "Exit slowly, no rush."),
    ],
    i18n: { title: { fr: "Silence profond", en: "Deep stillness" } },
    premium_only: true,
  },

  // ── RESPIRATION ────────────────────────────────────────────────────────────
  {
    slug: "breath-478-1min",
    category: "breathing",
    title: "Respiration 4-7-8",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["calme", "sommeil"],
    contraindications: ["grossesse_avis_medecin"],
    steps: [
      step(1, "Inspire par le nez 4 secondes.", "Inhale through nose 4 seconds."),
      step(2, "Retiens 7 secondes.", "Hold 7 seconds."),
      step(3, "Expire par la bouche 8 secondes.", "Exhale through mouth 8 seconds."),
      step(4, "Répète 3 cycles.", "Repeat 3 cycles."),
    ],
    i18n: { title: { fr: "Respiration 4-7-8", en: "4-7-8 breath" } },
    premium_only: false,
  },
  {
    slug: "breath-box-2min",
    category: "breathing",
    title: "Respiration carrée",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus", "calme"],
    contraindications: [],
    steps: [
      step(1, "Inspire 4 secondes.", "Inhale 4 seconds."),
      step(2, "Retiens 4 secondes.", "Hold 4 seconds."),
      step(3, "Expire 4 secondes.", "Exhale 4 seconds."),
      step(4, "Pause 4 secondes. Recommence.", "Pause 4 seconds. Repeat."),
    ],
    i18n: { title: { fr: "Respiration carrée", en: "Box breathing" } },
    premium_only: false,
  },
  {
    slug: "breath-coherence-5min",
    category: "breathing",
    title: "Cohérence cardiaque",
    duration_seconds: 300,
    intensity: "gentle",
    goal_tags: ["calme", "focus"],
    contraindications: [],
    steps: [
      step(1, "Inspire 5 secondes.", "Inhale 5 seconds."),
      step(2, "Expire 5 secondes.", "Exhale 5 seconds."),
      step(3, "Maintiens ce rythme régulier.", "Keep this steady rhythm."),
      step(4, "30 cycles ≈ 5 minutes.", "30 cycles ≈ 5 minutes."),
    ],
    i18n: { title: { fr: "Cohérence cardiaque", en: "Heart coherence" } },
    premium_only: false,
  },
  {
    slug: "breath-alternate-nostril-3min",
    category: "breathing",
    title: "Respiration alternée",
    duration_seconds: 180,
    intensity: "medium",
    goal_tags: ["focus", "calme"],
    contraindications: ["sinusite_aigue"],
    steps: [
      step(1, "Pouce droit sur narine droite.", "Right thumb on right nostril."),
      step(2, "Inspire par la narine gauche.", "Inhale through left nostril."),
      step(3, "Annulaire sur narine gauche, expire à droite.", "Ring finger on left nostril, exhale right."),
      step(4, "Inspire à droite, expire à gauche. Continue.", "Inhale right, exhale left. Continue."),
    ],
    i18n: { title: { fr: "Respiration alternée", en: "Alternate nostril" } },
    premium_only: false,
  },
  {
    slug: "breath-energizing-2min",
    category: "breathing",
    title: "Souffle énergisant",
    duration_seconds: 120,
    intensity: "medium",
    goal_tags: ["energie"],
    contraindications: ["hypertension", "grossesse_avis_medecin"],
    steps: [
      step(1, "Inspire courte par le nez (1s).", "Quick inhale through nose (1s)."),
      step(2, "Expire courte et active (1s).", "Quick active exhale (1s)."),
      step(3, "20 cycles puis pause normale 30s.", "20 cycles then normal pause 30s."),
      step(4, "Termine par 3 respirations lentes.", "End with 3 slow breaths."),
    ],
    i18n: { title: { fr: "Souffle énergisant", en: "Energizing breath" } },
    premium_only: false,
  },
  {
    slug: "breath-belly-1min",
    category: "breathing",
    title: "Respiration ventrale",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["calme", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Une main sur le ventre.", "One hand on the belly."),
      step(2, "Inspire en gonflant le ventre 4s.", "Inhale, expanding belly 4s."),
      step(3, "Expire en dégonflant 6s.", "Exhale, deflating 6s."),
      step(4, "6 cycles suffisent.", "6 cycles is enough."),
    ],
    i18n: { title: { fr: "Respiration ventrale", en: "Belly breath" } },
    premium_only: false,
  },
  {
    slug: "breath-sigh-30s",
    category: "breathing",
    title: "Soupir physiologique",
    duration_seconds: 30,
    intensity: "gentle",
    goal_tags: ["calme", "release"],
    contraindications: [],
    steps: [
      step(1, "Inspire long par le nez.", "Long inhale through the nose."),
      step(2, "Petite seconde inspiration en plus.", "Small extra second inhale."),
      step(3, "Expire long par la bouche.", "Long exhale through the mouth."),
      step(4, "Répète 3 fois.", "Repeat 3 times."),
    ],
    i18n: { title: { fr: "Soupir physiologique", en: "Physiological sigh" } },
    premium_only: false,
  },
  {
    slug: "breath-ujjayi-3min",
    category: "breathing",
    title: "Souffle de l'océan",
    duration_seconds: 180,
    intensity: "medium",
    goal_tags: ["focus", "calme"],
    contraindications: [],
    steps: [
      step(1, "Bouche fermée, légère contraction de la gorge.", "Mouth closed, slight throat contraction."),
      step(2, "Inspire long par le nez avec un son doux.", "Long inhale through nose with soft sound."),
      step(3, "Expire long par le nez avec le même son.", "Long exhale through nose with same sound."),
      step(4, "Le son ressemble à des vagues.", "Sound resembles waves."),
    ],
    i18n: { title: { fr: "Souffle de l'océan", en: "Ocean breath" } },
    premium_only: false,
  },
  {
    slug: "breath-counted-2min",
    category: "breathing",
    title: "Compter le souffle",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "Inspire — compte 1.", "Inhale — count 1."),
      step(2, "Expire — compte 2.", "Exhale — count 2."),
      step(3, "Continue jusqu'à 10, recommence à 1.", "Continue to 10, restart at 1."),
      step(4, "Si tu perds le compte : reprends à 1.", "If you lose count: restart at 1."),
    ],
    i18n: { title: { fr: "Compter le souffle", en: "Counted breath" } },
    premium_only: false,
  },
  {
    slug: "breath-extended-exhale-2min",
    category: "breathing",
    title: "Expir long apaisant",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["sommeil", "calme"],
    contraindications: [],
    steps: [
      step(1, "Inspire 4 secondes.", "Inhale 4 seconds."),
      step(2, "Expire 8 secondes.", "Exhale 8 seconds."),
      step(3, "L'expir long signale au système nerveux : repos.", "Long exhale signals the nervous system: rest."),
      step(4, "10 cycles environ.", "About 10 cycles."),
    ],
    i18n: { title: { fr: "Expir long apaisant", en: "Calming long exhale" } },
    premium_only: false,
  },
  {
    slug: "breath-three-part-3min",
    category: "breathing",
    title: "Souffle en trois parties",
    duration_seconds: 180,
    intensity: "medium",
    goal_tags: ["calme", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Inspire dans le ventre, puis le diaphragme, puis le haut de la poitrine.", "Inhale into belly, then diaphragm, then upper chest."),
      step(2, "Expire dans l'ordre inverse.", "Exhale in reverse order."),
      step(3, "Lent, sans forcer.", "Slow, no forcing."),
      step(4, "Continue 8-10 cycles.", "Continue 8-10 cycles."),
    ],
    i18n: { title: { fr: "Souffle en trois parties", en: "Three-part breath" } },
    premium_only: false,
  },
  {
    slug: "breath-reset-1min",
    category: "breathing",
    title: "Réinitialisation 1 min",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["calme", "focus"],
    contraindications: [],
    steps: [
      step(1, "Tu peux fermer les yeux.", "You can close your eyes."),
      step(2, "5 respirations lentes, profondes.", "5 slow, deep breaths."),
      step(3, "À chaque expir, relâche les épaules.", "On each exhale, release the shoulders."),
      step(4, "Reviens, plus posé·e.", "Return, more settled."),
    ],
    i18n: { title: { fr: "Réinitialisation 1 min", en: "1 min reset" } },
    premium_only: false,
  },

  // ── MANTRA ─────────────────────────────────────────────────────────────────
  {
    slug: "mantra-so-hum-2min",
    category: "mantra",
    title: "So Hum",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite", "calme"],
    contraindications: [],
    steps: [
      step(1, "Inspire — silencieusement : 'So'.", "Inhale — silently: 'So'."),
      step(2, "Expire — silencieusement : 'Hum'.", "Exhale — silently: 'Hum'."),
      step(3, "Laisse le rythme s'installer.", "Let the rhythm settle."),
      step(4, "Continue 2 minutes.", "Continue for 2 minutes."),
    ],
    i18n: { title: { fr: "So Hum", en: "So Hum" } },
    premium_only: false,
  },
  {
    slug: "mantra-i-am-here-1min",
    category: "mantra",
    title: "Je suis ici",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["ancrage", "calme"],
    contraindications: [],
    steps: [
      step(1, "Inspire.", "Inhale."),
      step(2, "Expire en pensant : 'Je suis ici.'", "Exhale thinking: 'I am here.'"),
      step(3, "Répète 10 fois.", "Repeat 10 times."),
      step(4, "Sens où tu es vraiment.", "Feel where you really are."),
    ],
    i18n: { title: { fr: "Je suis ici", en: "I am here" } },
    premium_only: false,
  },
  {
    slug: "mantra-hooponopono-3min",
    category: "mantra",
    title: "Ho'oponopono",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["spiritualite", "release"],
    contraindications: [],
    steps: [
      step(1, "Pense à une situation à apaiser.", "Think of a situation to soothe."),
      step(2, "Dis intérieurement : 'Désolé·e.'", "Internally say: 'I'm sorry.'"),
      step(3, "Puis : 'Pardon. Merci. Je t'aime.'", "Then: 'Please forgive me. Thank you. I love you.'"),
      step(4, "Répète, lentement.", "Repeat, slowly."),
    ],
    i18n: { title: { fr: "Ho'oponopono", en: "Ho'oponopono" } },
    premium_only: false,
  },
  {
    slug: "mantra-om-2min",
    category: "mantra",
    title: "Om",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Inspire profondément.", "Inhale deeply."),
      step(2, "Sur l'expir, prononce 'Ooommm' lentement.", "On the exhale, sound 'Ooommm' slowly."),
      step(3, "Sens la vibration dans la poitrine.", "Feel the vibration in the chest."),
      step(4, "10 répétitions.", "10 repetitions."),
    ],
    i18n: { title: { fr: "Om", en: "Om" } },
    premium_only: false,
  },
  {
    slug: "mantra-thank-you-1min",
    category: "mantra",
    title: "Merci",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Inspire.", "Inhale."),
      step(2, "Expire en pensant 'Merci.'", "Exhale thinking 'Thank you.'"),
      step(3, "Pour rien en particulier — ou pour tout.", "For nothing in particular — or for everything."),
      step(4, "10 cycles.", "10 cycles."),
    ],
    i18n: { title: { fr: "Merci", en: "Thank you" } },
    premium_only: false,
  },
  {
    slug: "mantra-i-allow-2min",
    category: "mantra",
    title: "Je m'autorise",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Inspire.", "Inhale."),
      step(2, "Expire : 'Je m'autorise à être là.'", "Exhale: 'I allow myself to be here.'"),
      step(3, "Puis : 'Je m'autorise à ralentir.'", "Then: 'I allow myself to slow down.'"),
      step(4, "Puis : 'Je m'autorise à exister.'", "Then: 'I allow myself to exist.'"),
    ],
    i18n: { title: { fr: "Je m'autorise", en: "I allow myself" } },
    premium_only: false,
  },
  {
    slug: "mantra-let-go-1min",
    category: "mantra",
    title: "Je relâche",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["release", "calme"],
    contraindications: [],
    steps: [
      step(1, "Inspire les épaules vers le haut.", "Inhale shoulders up."),
      step(2, "Expire en disant 'Je relâche.'", "Exhale saying 'I release.'"),
      step(3, "Les épaules redescendent.", "Shoulders drop."),
      step(4, "Répète 5 fois.", "Repeat 5 times."),
    ],
    i18n: { title: { fr: "Je relâche", en: "I release" } },
    premium_only: false,
  },
  {
    slug: "mantra-courage-2min",
    category: "mantra",
    title: "Mantra du courage",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["courage", "energie"],
    contraindications: [],
    steps: [
      step(1, "'Je peux faire ça.'", "'I can do this.'"),
      step(2, "'Une chose à la fois.'", "'One step at a time.'"),
      step(3, "'Je fais déjà beaucoup.'", "'I'm already doing a lot.'"),
      step(4, "Répète celui qui te touche.", "Repeat the one that resonates."),
    ],
    i18n: { title: { fr: "Mantra du courage", en: "Courage mantra" } },
    premium_only: false,
  },
  {
    slug: "mantra-peace-3min",
    category: "mantra",
    title: "Mantra de paix",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["calme", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "'Je suis en paix.'", "'I am at peace.'"),
      step(2, "'Tout est en ordre.'", "'All is well.'"),
      step(3, "'Je n'ai rien à prouver.'", "'I have nothing to prove.'"),
      step(4, "Choisis-en un et reste avec.", "Pick one and stay with it."),
    ],
    i18n: { title: { fr: "Mantra de paix", en: "Peace mantra" } },
    premium_only: false,
  },
  {
    slug: "mantra-abundance-2min",
    category: "mantra",
    title: "Mantra d'abondance",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "'J'ai assez. Je suis assez.'", "'I have enough. I am enough.'"),
      step(2, "'Ce qui est juste pour moi vient à moi.'", "'What is right for me comes to me.'"),
      step(3, "Répète sans forcer la conviction.", "Repeat without forcing belief."),
      step(4, "Laisse les phrases s'imprégner.", "Let the phrases settle."),
    ],
    i18n: { title: { fr: "Mantra d'abondance", en: "Abundance mantra" } },
    premium_only: false,
  },
  {
    slug: "mantra-evening-1min",
    category: "mantra",
    title: "Mantra du soir",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["sommeil", "calme"],
    contraindications: [],
    steps: [
      step(1, "'La journée est terminée.'", "'The day is done.'"),
      step(2, "'Je peux poser les choses.'", "'I can set things down.'"),
      step(3, "'Demain est demain.'", "'Tomorrow is tomorrow.'"),
      step(4, "Souffle long.", "Long exhale."),
    ],
    i18n: { title: { fr: "Mantra du soir", en: "Evening mantra" } },
    premium_only: false,
  },
  {
    slug: "mantra-here-now-30s",
    category: "mantra",
    title: "Ici, maintenant",
    duration_seconds: 30,
    intensity: "gentle",
    goal_tags: ["ancrage", "focus"],
    contraindications: [],
    steps: [
      step(1, "Inspire : 'Ici.'", "Inhale: 'Here.'"),
      step(2, "Expire : 'Maintenant.'", "Exhale: 'Now.'"),
      step(3, "10 cycles.", "10 cycles."),
    ],
    i18n: { title: { fr: "Ici, maintenant", en: "Here, now" } },
    premium_only: false,
  },

  // ── MUDRA ──────────────────────────────────────────────────────────────────
  {
    slug: "mudra-gyan-3min",
    category: "mudra",
    title: "Gyan mudra",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["focus", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Joins le pouce et l'index, autres doigts détendus.", "Join thumb and index, other fingers relaxed."),
      step(2, "Pose les mains sur les genoux, paumes vers le ciel.", "Rest hands on knees, palms up."),
      step(3, "Respire calmement.", "Breathe calmly."),
      step(4, "Reste 3 minutes.", "Hold for 3 minutes."),
    ],
    i18n: { title: { fr: "Gyan mudra", en: "Gyan mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-anjali-1min",
    category: "mudra",
    title: "Anjali (mains jointes)",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["spiritualite", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Joins les paumes au cœur.", "Join palms at the heart."),
      step(2, "Légère pression entre les paumes.", "Slight pressure between palms."),
      step(3, "Respire dans cet espace.", "Breathe into that space."),
      step(4, "1 minute.", "1 minute."),
    ],
    i18n: { title: { fr: "Anjali (mains jointes)", en: "Anjali (joined hands)" } },
    premium_only: false,
  },
  {
    slug: "mudra-prana-2min",
    category: "mudra",
    title: "Prana mudra",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["energie"],
    contraindications: [],
    steps: [
      step(1, "Pouce + auriculaire + annulaire.", "Thumb + pinky + ring finger."),
      step(2, "Index et majeur tendus.", "Index and middle extended."),
      step(3, "Mains posées, paumes vers le ciel.", "Hands resting, palms up."),
      step(4, "Respire 2 minutes.", "Breathe for 2 minutes."),
    ],
    i18n: { title: { fr: "Prana mudra", en: "Prana mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-shuni-2min",
    category: "mudra",
    title: "Shuni mudra",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus", "calme"],
    contraindications: [],
    steps: [
      step(1, "Joins le pouce et le majeur.", "Join thumb and middle finger."),
      step(2, "Détends les autres doigts.", "Relax the other fingers."),
      step(3, "Mains sur genoux.", "Hands on knees."),
      step(4, "2 minutes de respiration calme.", "2 minutes of calm breath."),
    ],
    i18n: { title: { fr: "Shuni mudra", en: "Shuni mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-surya-2min",
    category: "mudra",
    title: "Surya mudra",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["energie"],
    contraindications: [],
    steps: [
      step(1, "Pli l'annulaire vers la base du pouce.", "Fold ring finger to thumb base."),
      step(2, "Pouce sur l'annulaire, autres doigts tendus.", "Thumb over ring, other fingers extended."),
      step(3, "Mains sur les cuisses.", "Hands on thighs."),
      step(4, "2 minutes.", "2 minutes."),
    ],
    i18n: { title: { fr: "Surya mudra", en: "Surya mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-apana-3min",
    category: "mudra",
    title: "Apana mudra",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["release", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Pouce + majeur + annulaire ensemble.", "Thumb + middle + ring together."),
      step(2, "Index et auriculaire détendus.", "Index and pinky relaxed."),
      step(3, "Paumes vers le ciel.", "Palms up."),
      step(4, "3 minutes de respiration ventrale.", "3 minutes of belly breath."),
    ],
    i18n: { title: { fr: "Apana mudra", en: "Apana mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-heart-opening-1min",
    category: "mudra",
    title: "Mudra du cœur ouvert",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["spiritualite", "release"],
    contraindications: [],
    steps: [
      step(1, "Mains posées sur le cœur, l'une sur l'autre.", "Hands on the heart, one on top of the other."),
      step(2, "Sens la chaleur sous tes paumes.", "Feel the warmth under your palms."),
      step(3, "Respire dans cet espace.", "Breathe into that space."),
      step(4, "1 minute.", "1 minute."),
    ],
    i18n: { title: { fr: "Mudra du cœur ouvert", en: "Open heart mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-grounding-2min",
    category: "mudra",
    title: "Mudra d'ancrage",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["ancrage"],
    contraindications: [],
    steps: [
      step(1, "Paumes vers le sol sur les cuisses.", "Palms down on thighs."),
      step(2, "Imagine que ton poids descend.", "Imagine your weight sinking."),
      step(3, "Respire lentement.", "Breathe slowly."),
      step(4, "2 minutes.", "2 minutes."),
    ],
    i18n: { title: { fr: "Mudra d'ancrage", en: "Grounding mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-receiving-1min",
    category: "mudra",
    title: "Mudra de réception",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Paumes vers le ciel sur les cuisses.", "Palms up on thighs."),
      step(2, "Imagine que tu reçois — sans rien forcer.", "Imagine you're receiving — no forcing."),
      step(3, "Respire calmement.", "Breathe calmly."),
      step(4, "1 minute.", "1 minute."),
    ],
    i18n: { title: { fr: "Mudra de réception", en: "Receiving mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-balance-3min",
    category: "mudra",
    title: "Mudra d'équilibre",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["calme", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Une paume vers le ciel, l'autre vers le sol.", "One palm up, one palm down."),
      step(2, "Inverse à mi-temps.", "Switch halfway through."),
      step(3, "Respire en cohérence cardiaque.", "Breathe in heart coherence."),
      step(4, "Total 3 minutes.", "Total 3 minutes."),
    ],
    i18n: { title: { fr: "Mudra d'équilibre", en: "Balance mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-fear-release-2min",
    category: "mudra",
    title: "Mudra anti-peur",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["release", "courage"],
    contraindications: [],
    steps: [
      step(1, "Index et majeur droits, autres doigts repliés.", "Index and middle straight, others folded."),
      step(2, "Main droite levée à hauteur d'épaule.", "Right hand at shoulder height."),
      step(3, "Respire calmement.", "Breathe calmly."),
      step(4, "2 minutes.", "2 minutes."),
    ],
    i18n: { title: { fr: "Mudra anti-peur", en: "Fear-release mudra" } },
    premium_only: false,
  },
  {
    slug: "mudra-clarity-2min",
    category: "mudra",
    title: "Mudra de clarté",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "Pouce + index + majeur ensemble.", "Thumb + index + middle together."),
      step(2, "Annulaire et auriculaire tendus.", "Ring and pinky extended."),
      step(3, "Mains sur les cuisses.", "Hands on thighs."),
      step(4, "2 minutes.", "2 minutes."),
    ],
    i18n: { title: { fr: "Mudra de clarté", en: "Clarity mudra" } },
    premium_only: false,
  },

  // ── MOUVEMENT ──────────────────────────────────────────────────────────────
  {
    slug: "move-shoulders-roll-1min",
    category: "movement",
    title: "Rotation des épaules",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["release", "calme"],
    contraindications: ["epaule_blessee"],
    steps: [
      step(1, "Lève les épaules vers les oreilles.", "Lift shoulders toward ears."),
      step(2, "Roule en arrière, lentement.", "Roll backward, slowly."),
      step(3, "5 cercles arrière, 5 cercles avant.", "5 backward circles, 5 forward."),
      step(4, "Termine immobile, conscient·e.", "End still, aware."),
    ],
    i18n: { title: { fr: "Rotation des épaules", en: "Shoulder rolls" } },
    premium_only: false,
  },
  {
    slug: "move-neck-stretch-2min",
    category: "movement",
    title: "Étirements de la nuque",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["release"],
    contraindications: ["cervicales_blessees"],
    steps: [
      step(1, "Oreille vers épaule droite, 30s.", "Right ear to shoulder, 30s."),
      step(2, "Retour, oreille vers épaule gauche, 30s.", "Return, left ear to shoulder, 30s."),
      step(3, "Menton vers poitrine, 30s.", "Chin to chest, 30s."),
      step(4, "Retour neutre, respire.", "Return neutral, breathe."),
    ],
    i18n: { title: { fr: "Étirements de la nuque", en: "Neck stretches" } },
    premium_only: false,
  },
  {
    slug: "move-cat-cow-2min",
    category: "movement",
    title: "Chat-vache",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["release", "ancrage"],
    contraindications: ["dos_blessure_aigue"],
    steps: [
      step(1, "À quatre pattes, dos neutre.", "On all fours, neutral back."),
      step(2, "Inspire : creuse le dos, regarde devant.", "Inhale: arch back, look forward."),
      step(3, "Expire : arrondis le dos, menton rentré.", "Exhale: round back, chin tucked."),
      step(4, "10 cycles lents.", "10 slow cycles."),
    ],
    i18n: { title: { fr: "Chat-vache", en: "Cat-cow" } },
    premium_only: false,
  },
  {
    slug: "move-side-stretch-1min",
    category: "movement",
    title: "Étirement latéral debout",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["release", "energie"],
    contraindications: [],
    steps: [
      step(1, "Debout, bras gauche au-dessus.", "Standing, left arm overhead."),
      step(2, "Penche-toi à droite, 20s.", "Bend right, 20s."),
      step(3, "Change de côté.", "Switch sides."),
      step(4, "Respire largement.", "Breathe widely."),
    ],
    i18n: { title: { fr: "Étirement latéral debout", en: "Standing side stretch" } },
    premium_only: false,
  },
  {
    slug: "move-mindful-walk-3min",
    category: "movement",
    title: "Marche consciente",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["ancrage", "focus"],
    contraindications: [],
    steps: [
      step(1, "Marche lentement, talon-pointe.", "Walk slowly, heel-toe."),
      step(2, "Sens chaque pas, sans vitesse.", "Feel each step, no rush."),
      step(3, "Respiration synchronisée 4 pas / 4 pas.", "Breath synced 4 steps / 4 steps."),
      step(4, "Pose-toi en fin.", "Settle at the end."),
    ],
    i18n: { title: { fr: "Marche consciente", en: "Mindful walk" } },
    premium_only: false,
  },
  {
    slug: "move-shake-30s",
    category: "movement",
    title: "Secouer le stress",
    duration_seconds: 30,
    intensity: "medium",
    goal_tags: ["release", "energie"],
    contraindications: ["dos_blessure_aigue"],
    steps: [
      step(1, "Debout, secoue les bras et les jambes.", "Standing, shake arms and legs."),
      step(2, "Tout le corps tremble doucement.", "Whole body shakes lightly."),
      step(3, "Imagine que tu déposes ce qui pèse.", "Imagine setting down what weighs."),
      step(4, "Stop. Respire.", "Stop. Breathe."),
    ],
    i18n: { title: { fr: "Secouer le stress", en: "Stress shake-out" } },
    premium_only: false,
  },
  {
    slug: "move-sun-greeting-3min",
    category: "movement",
    title: "Salutation au matin",
    duration_seconds: 180,
    intensity: "medium",
    goal_tags: ["energie", "ancrage"],
    contraindications: ["genou_blesse"],
    steps: [
      step(1, "Debout, mains jointes au cœur.", "Standing, hands at heart."),
      step(2, "Bras vers le ciel, légère extension arrière.", "Arms up, slight backbend."),
      step(3, "Flexion avant, mains vers le sol.", "Forward fold, hands toward floor."),
      step(4, "Remonte, retour mains au cœur.", "Rise, hands back to heart."),
      step(5, "Répète 3 fois.", "Repeat 3 times."),
    ],
    i18n: { title: { fr: "Salutation au matin", en: "Morning greeting" } },
    premium_only: false,
  },
  {
    slug: "move-figure-eight-1min",
    category: "movement",
    title: "Bassin en huit",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["release", "energie"],
    contraindications: [],
    steps: [
      step(1, "Debout, genoux légèrement fléchis.", "Standing, knees slightly bent."),
      step(2, "Dessine un huit horizontal avec le bassin.", "Draw a horizontal 8 with the hips."),
      step(3, "Sens-le partout dans le ventre.", "Feel it everywhere in the belly."),
      step(4, "Inverse le sens à mi-temps.", "Reverse direction halfway."),
    ],
    i18n: { title: { fr: "Bassin en huit", en: "Hip figure-8" } },
    premium_only: false,
  },
  {
    slug: "move-tension-release-2min",
    category: "movement",
    title: "Contracter-relâcher",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["release", "calme"],
    contraindications: [],
    steps: [
      step(1, "Contracte les pieds 5s, relâche.", "Tense feet 5s, release."),
      step(2, "Mollets, cuisses, fessiers — chacun 5s.", "Calves, thighs, glutes — each 5s."),
      step(3, "Ventre, mains, bras, visage.", "Belly, hands, arms, face."),
      step(4, "Termine, tout le corps lâche.", "End, whole body releases."),
    ],
    i18n: { title: { fr: "Contracter-relâcher", en: "Tense and release" } },
    premium_only: false,
  },
  {
    slug: "move-spinal-twist-2min",
    category: "movement",
    title: "Torsion assise",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["release"],
    contraindications: ["dos_blessure_aigue", "grossesse_avis_medecin"],
    steps: [
      step(1, "Assis·e, jambes croisées.", "Seated, legs crossed."),
      step(2, "Main droite sur genou gauche.", "Right hand on left knee."),
      step(3, "Tourne doucement à gauche, 30s.", "Slowly twist left, 30s."),
      step(4, "Change de côté.", "Switch sides."),
    ],
    i18n: { title: { fr: "Torsion assise", en: "Seated twist" } },
    premium_only: false,
  },
  {
    slug: "move-foot-massage-1min",
    category: "movement",
    title: "Auto-massage des pieds",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["ancrage", "calme"],
    contraindications: [],
    steps: [
      step(1, "Croise une cheville sur ton genou.", "Cross one ankle over your knee."),
      step(2, "Masse la voûte plantaire avec les pouces.", "Massage the arch with your thumbs."),
      step(3, "Insiste où ça serre.", "Linger where it's tight."),
      step(4, "Change de pied.", "Switch feet."),
    ],
    i18n: { title: { fr: "Auto-massage des pieds", en: "Foot self-massage" } },
    premium_only: false,
  },
  {
    slug: "move-childs-pose-2min",
    category: "movement",
    title: "Posture de l'enfant",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["calme", "release"],
    contraindications: ["genou_blesse"],
    steps: [
      step(1, "À genoux, gros orteils joints.", "On knees, big toes touching."),
      step(2, "Assieds-toi sur tes talons.", "Sit on your heels."),
      step(3, "Penche-toi en avant, front au sol.", "Fold forward, forehead to floor."),
      step(4, "Bras devant ou le long du corps. Respire.", "Arms forward or by sides. Breathe."),
    ],
    i18n: { title: { fr: "Posture de l'enfant", en: "Child's pose" } },
    premium_only: false,
  },

  // ── APPRENTISSAGE ──────────────────────────────────────────────────────────
  {
    slug: "learn-stoic-control-2min",
    category: "learning",
    title: "Ce qui dépend de toi (stoïcisme)",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus", "calme"],
    contraindications: [],
    steps: [
      step(1, "Liste mentalement 3 choses qui te préoccupent.", "Mentally list 3 things on your mind."),
      step(2, "Pour chacune : dépend de moi ? Pas de moi ?", "For each: depends on me? Not on me?"),
      step(3, "Mets ton énergie sur celles qui dépendent de toi.", "Put energy on those that depend on you."),
      step(4, "Lâche les autres pour cette minute.", "Release the others for this minute."),
    ],
    i18n: { title: { fr: "Ce qui dépend de toi (stoïcisme)", en: "What's in your control (Stoicism)" } },
    premium_only: false,
  },
  {
    slug: "learn-bias-confirmation-2min",
    category: "learning",
    title: "Le biais de confirmation",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "On voit ce qu'on s'attend à voir.", "We see what we expect to see."),
      step(2, "Quel pré-jugement t'a déjà piégé·e ?", "What pre-judgment has tripped you up?"),
      step(3, "Aujourd'hui : essaie de remarquer 1 contre-exemple.", "Today: try to notice 1 counter-example."),
      step(4, "Ralentir = remarquer.", "Slowing down = noticing."),
    ],
    i18n: { title: { fr: "Le biais de confirmation", en: "Confirmation bias" } },
    premium_only: false,
  },
  {
    slug: "learn-attention-residue-1min",
    category: "learning",
    title: "Le résidu d'attention",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "Quand tu changes de tâche, ton attention reste un peu derrière.", "When you switch tasks, attention lingers."),
      step(2, "Une transition consciente coupe le résidu.", "A conscious transition cuts the residue."),
      step(3, "3 respirations entre 2 tâches suffisent.", "3 breaths between tasks is enough."),
      step(4, "Essaie aujourd'hui.", "Try it today."),
    ],
    i18n: { title: { fr: "Le résidu d'attention", en: "Attention residue" } },
    premium_only: false,
  },
  {
    slug: "learn-vagus-nerve-2min",
    category: "learning",
    title: "Le nerf vague (basique)",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["calme"],
    contraindications: [],
    steps: [
      step(1, "Le nerf vague relie le cerveau aux organes.", "The vagus nerve connects brain to organs."),
      step(2, "Un expir long stimule sa branche apaisante.", "A long exhale stimulates its calming branch."),
      step(3, "C'est pourquoi 'expirer plus que tu inspires' calme.", "That's why 'exhale longer than inhale' calms."),
      step(4, "Souvenir-toi : long expir = calme.", "Remember: long exhale = calm."),
    ],
    i18n: { title: { fr: "Le nerf vague (basique)", en: "Vagus nerve (basics)" } },
    premium_only: false,
  },
  {
    slug: "learn-implementation-intent-1min",
    category: "learning",
    title: "Intention d'implémentation",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "'Je veux faire X' échoue souvent.", "'I want to do X' often fails."),
      step(2, "'Quand Y arrive, je fais X' marche mieux.", "'When Y happens, I do X' works better."),
      step(3, "Trouve UN couple Y→X pour aujourd'hui.", "Find ONE Y→X pair for today."),
      step(4, "Note-le mentalement.", "Note it mentally."),
    ],
    i18n: { title: { fr: "Intention d'implémentation", en: "Implementation intention" } },
    premium_only: false,
  },
  {
    slug: "learn-rumi-poem-2min",
    category: "learning",
    title: "Sagesse de Rumi",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "'La blessure est l'endroit où la lumière entre.'", "'The wound is where the light enters.'"),
      step(2, "Pense à une difficulté récente.", "Think of a recent difficulty."),
      step(3, "Quelle lumière a-t-elle laissé passer ?", "What light did it let through?"),
      step(4, "Reste avec cette idée 30s.", "Stay with that idea 30s."),
    ],
    i18n: { title: { fr: "Sagesse de Rumi", en: "Rumi's wisdom" } },
    premium_only: false,
  },
  {
    slug: "learn-flow-state-2min",
    category: "learning",
    title: "Le flow",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "Le flow = défi juste au-dessus de tes capacités.", "Flow = challenge just above your skill."),
      step(2, "Trop facile → ennui. Trop dur → angoisse.", "Too easy → boredom. Too hard → anxiety."),
      step(3, "Sur quoi pourrais-tu trouver ton 'juste' aujourd'hui ?", "Where could you find your 'just right' today?"),
      step(4, "1 micro-décision suffit.", "One micro-decision is enough."),
    ],
    i18n: { title: { fr: "Le flow", en: "Flow state" } },
    premium_only: false,
  },
  {
    slug: "learn-self-talk-2min",
    category: "learning",
    title: "Le dialogue intérieur",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["calme"],
    contraindications: [],
    steps: [
      step(1, "Comment tu te parles change ce que tu vis.", "How you talk to yourself shapes what you live."),
      step(2, "Note une phrase que tu te dis souvent.", "Notice a phrase you tell yourself often."),
      step(3, "Tu la dirais à ton meilleur·e ami·e ?", "Would you say it to your best friend?"),
      step(4, "Si non — adoucis-la pour toi.", "If not — soften it for yourself."),
    ],
    i18n: { title: { fr: "Le dialogue intérieur", en: "Self-talk" } },
    premium_only: false,
  },
  {
    slug: "learn-habit-stack-1min",
    category: "learning",
    title: "Empiler les habitudes",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["focus"],
    contraindications: [],
    steps: [
      step(1, "Greffe une nouvelle habitude sur une ancienne.", "Stack a new habit onto an old one."),
      step(2, "Ex : après le café → 1 min de respiration.", "Ex: after coffee → 1 min of breath."),
      step(3, "Quel ancrage existe déjà chez toi ?", "What anchor already exists for you?"),
      step(4, "Greffe une micro-action légère.", "Stack a light micro-action."),
    ],
    i18n: { title: { fr: "Empiler les habitudes", en: "Habit stacking" } },
    premium_only: false,
  },
  {
    slug: "learn-impermanence-2min",
    category: "learning",
    title: "L'impermanence",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite", "calme"],
    contraindications: [],
    steps: [
      step(1, "Tout passe — les bons moments comme les durs.", "Everything passes — the good and the hard."),
      step(2, "Ce que tu vis maintenant aussi.", "What you live now too."),
      step(3, "Pas une excuse pour fuir : un rappel pour ne pas s'agripper.", "Not an excuse to flee: a reminder not to cling."),
      step(4, "Reste avec l'idée 30s.", "Stay with the idea 30s."),
    ],
    i18n: { title: { fr: "L'impermanence", en: "Impermanence" } },
    premium_only: false,
  },

  // ── REPROGRAMMATION ────────────────────────────────────────────────────────
  {
    slug: "reprog-confidence-3min",
    category: "reprogramming",
    title: "Affirmations confiance",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["courage", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Inspire profondément.", "Inhale deeply."),
      step(2, "'Je peux compter sur moi.'", "'I can count on myself.'"),
      step(3, "'J'apprends à chaque pas.'", "'I learn with each step.'"),
      step(4, "'Je n'ai rien à prouver.'", "'I have nothing to prove.'"),
      step(5, "Répète celle qui résonne.", "Repeat the one that resonates."),
    ],
    i18n: { title: { fr: "Affirmations confiance", en: "Confidence affirmations" } },
    premium_only: false,
  },
  {
    slug: "reprog-abundance-3min",
    category: "reprogramming",
    title: "Visualisation abondance",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Ferme les yeux.", "Close your eyes."),
      step(2, "Imagine un lieu où tu te sens 'assez'.", "Picture a place where you feel 'enough'."),
      step(3, "Note : couleurs, sons, odeurs, sensations.", "Notice: colors, sounds, smells, sensations."),
      step(4, "Reste 1 minute. Reviens.", "Stay 1 minute. Return."),
    ],
    i18n: { title: { fr: "Visualisation abondance", en: "Abundance visualization" } },
    premium_only: false,
  },
  {
    slug: "reprog-evening-anchor-2min",
    category: "reprogramming",
    title: "Ancrage du soir",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["sommeil"],
    contraindications: [],
    steps: [
      step(1, "Pose une main sur le ventre, l'autre sur le cœur.", "One hand on belly, one on heart."),
      step(2, "'Ma journée est terminée.'", "'My day is done.'"),
      step(3, "'Je peux poser tout ce que j'ai porté.'", "'I can set down what I carried.'"),
      step(4, "'Demain est demain.'", "'Tomorrow is tomorrow.'"),
    ],
    i18n: { title: { fr: "Ancrage du soir", en: "Evening anchor" } },
    premium_only: false,
  },
  {
    slug: "reprog-morning-intent-1min",
    category: "reprogramming",
    title: "Intention du matin",
    duration_seconds: 60,
    intensity: "gentle",
    goal_tags: ["focus", "energie"],
    contraindications: [],
    steps: [
      step(1, "Une seule intention pour aujourd'hui.", "One intention for today."),
      step(2, "Pas un objectif — un état d'esprit.", "Not a goal — a mindset."),
      step(3, "Ex : 'présent·e', 'patient·e', 'curieux·se'.", "Ex: 'present', 'patient', 'curious'."),
      step(4, "Répète-la 3 fois.", "Repeat it 3 times."),
    ],
    i18n: { title: { fr: "Intention du matin", en: "Morning intention" } },
    premium_only: false,
  },
  {
    slug: "reprog-self-worth-3min",
    category: "reprogramming",
    title: "Affirmations valeur propre",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["spiritualite"],
    contraindications: [],
    steps: [
      step(1, "'Je vaux indépendamment de ce que je produis.'", "'I'm worthy regardless of what I produce.'"),
      step(2, "'Je suis assez, tel·le que je suis.'", "'I am enough, as I am.'"),
      step(3, "'Je peux exister sans me justifier.'", "'I can exist without justifying.'"),
      step(4, "Reste avec celle qui pique.", "Stay with the one that stings."),
    ],
    i18n: { title: { fr: "Affirmations valeur propre", en: "Self-worth affirmations" } },
    premium_only: false,
  },
  {
    slug: "reprog-future-self-5min",
    category: "reprogramming",
    title: "Lettre du futur",
    duration_seconds: 300,
    intensity: "medium",
    goal_tags: ["courage", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Imagine ton futur 'toi' dans 1 an, apaisé·e.", "Picture your future self in 1 year, at peace."),
      step(2, "Que te dirait-iel ?", "What would they tell you?"),
      step(3, "Quelle phrase courte choisirait-iel ?", "What short phrase would they choose?"),
      step(4, "Note-la mentalement.", "Note it mentally."),
      step(5, "Garde-la pour aujourd'hui.", "Keep it for today."),
    ],
    i18n: { title: { fr: "Lettre du futur", en: "Letter from the future" } },
    premium_only: false,
  },
  {
    slug: "reprog-release-control-2min",
    category: "reprogramming",
    title: "Lâcher le contrôle",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["release", "calme"],
    contraindications: [],
    steps: [
      step(1, "Liste mentalement 1 chose hors de ton contrôle.", "List 1 thing out of your control."),
      step(2, "Imagine-la dans une boîte.", "Imagine it in a box."),
      step(3, "Pose la boîte à côté de toi.", "Set the box beside you."),
      step(4, "'Pour cet instant, je n'ai pas à la porter.'", "'For now, I don't have to carry it.'"),
    ],
    i18n: { title: { fr: "Lâcher le contrôle", en: "Release control" } },
    premium_only: false,
  },
  {
    slug: "reprog-forgiveness-3min",
    category: "reprogramming",
    title: "Pardon doux",
    duration_seconds: 180,
    intensity: "medium",
    goal_tags: ["release", "spiritualite"],
    contraindications: [],
    steps: [
      step(1, "Pense à toi, le·la 'toi' d'hier.", "Think of yesterday's you."),
      step(2, "'Tu as fait avec ce que tu avais.'", "'You did with what you had.'"),
      step(3, "'Je peux te pardonner — un peu, pas tout.'", "'I can forgive you — a little, not all.'"),
      step(4, "Le pardon est un chemin, pas un événement.", "Forgiveness is a path, not an event."),
    ],
    i18n: { title: { fr: "Pardon doux", en: "Soft forgiveness" } },
    premium_only: false,
  },
  {
    slug: "reprog-body-appreciation-2min",
    category: "reprogramming",
    title: "Reconnaissance au corps",
    duration_seconds: 120,
    intensity: "gentle",
    goal_tags: ["spiritualite", "calme"],
    contraindications: [],
    steps: [
      step(1, "Pose la main sur ton ventre.", "Place hand on your belly."),
      step(2, "'Merci de me digérer ce que je vis.'", "'Thank you for digesting what I live.'"),
      step(3, "Mains sur le cœur. 'Merci de battre.'", "Hands on heart. 'Thank you for beating.'"),
      step(4, "Mains sur la tête. 'Merci de penser.'", "Hands on head. 'Thank you for thinking.'"),
    ],
    i18n: { title: { fr: "Reconnaissance au corps", en: "Body appreciation" } },
    premium_only: false,
  },
  {
    slug: "reprog-safe-place-3min",
    category: "reprogramming",
    title: "Mon lieu refuge",
    duration_seconds: 180,
    intensity: "gentle",
    goal_tags: ["calme", "ancrage"],
    contraindications: [],
    steps: [
      step(1, "Imagine un lieu où tu te sens parfaitement à l'aise.", "Picture a place where you feel completely at ease."),
      step(2, "Réel ou inventé — peu importe.", "Real or imagined — doesn't matter."),
      step(3, "Note 3 détails sensoriels.", "Notice 3 sensory details."),
      step(4, "'Ce lieu existe en moi. J'y reviens quand je veux.'", "'This place exists in me. I return when I want.'"),
    ],
    i18n: { title: { fr: "Mon lieu refuge", en: "My safe place" } },
    premium_only: false,
  },
];

async function main() {
  // Sanity: check that schema kaia is reachable
  const { data: head, error: headErr } = await supabase.from("practices").select("id", { count: "exact", head: true });
  if (headErr) {
    console.error("Cannot reach kaia.practices:", headErr.message);
    process.exit(1);
  }

  console.log(`📊 Practices currently in DB: ${head ? "?" : "?"} (head check OK)`);
  console.log(`🌱 Upserting ${PRACTICES.length} practices…`);

  // Upsert by slug — chunks of 20 to avoid payload limits
  for (let i = 0; i < PRACTICES.length; i += 20) {
    const chunk = PRACTICES.slice(i, i + 20);
    const rows = chunk.map((p) => ({
      slug: p.slug,
      category: p.category,
      title: p.title,
      duration_seconds: p.duration_seconds,
      intensity: p.intensity,
      goal_tags: p.goal_tags,
      contraindications: p.contraindications,
      steps: p.steps,
      i18n: p.i18n,
      audio_assets: {},
      premium_only: p.premium_only,
      active: true,
    }));
    const { error } = await supabase.from("practices").upsert(rows, { onConflict: "slug" });
    if (error) {
      console.error(`❌ Upsert chunk ${i}-${i + chunk.length}:`, error.message);
      process.exit(1);
    }
    console.log(`  ✓ Chunk ${i + 1}-${i + chunk.length} OK`);
  }

  const { count, error: countErr } = await supabase
    .from("practices")
    .select("id", { count: "exact", head: true });
  if (countErr) {
    console.error("Count error:", countErr.message);
    process.exit(1);
  }
  console.log(`✅ Done. Total practices in DB: ${count}`);

  // Per-category breakdown
  const cats: Array<"meditation" | "breathing" | "mantra" | "mudra" | "movement" | "learning" | "reprogramming"> = [
    "meditation",
    "breathing",
    "mantra",
    "mudra",
    "movement",
    "learning",
    "reprogramming",
  ];
  console.log("📊 Breakdown:");
  for (const c of cats) {
    const { count: cCount } = await supabase
      .from("practices")
      .select("id", { count: "exact", head: true })
      .eq("category", c);
    console.log(`   ${c.padEnd(15)} → ${cCount}`);
  }
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
