import "dotenv/config";
import postgres from "postgres";

const sql = postgres(process.env.DATABASE_URL!, { ssl: "require" });

async function run() {
  const games = [
    {
      slug: "journal-du-jour",
      title: "Journal du Jour",
      category: "transversal",
      tokens_reward: 5,
      recurrence: "daily",
      description: "Enregistre ton humeur et énergie du jour",
      active: true,
    },
    {
      slug: "gratitude-matin",
      title: "Gratitude Matinale",
      category: "transversal",
      tokens_reward: 5,
      recurrence: "daily",
      description: "Note 3 gratitudes au réveil",
      active: true,
    },
    {
      slug: "intention-du-jour",
      title: "Intention du Jour",
      category: "transversal",
      tokens_reward: 5,
      recurrence: "daily",
      description: "Pose une intention pour ta journée",
      active: true,
    },
    {
      slug: "respiration-3min",
      title: "3 Minutes de Souffle",
      category: "transversal",
      tokens_reward: 10,
      recurrence: "daily",
      description: "3 minutes de cohérence cardiaque",
      active: true,
    },
    {
      slug: "check-energie",
      title: "Check Énergie",
      category: "transversal",
      tokens_reward: 3,
      recurrence: "daily",
      description: "Évalue ton niveau d'énergie",
      active: true,
    },
    {
      slug: "rituel-semaine",
      title: "Rituel de la Semaine",
      category: "transversal",
      tokens_reward: 25,
      recurrence: "weekly",
      description: "Participe au rituel hebdomadaire",
      active: true,
    },
    {
      slug: "bilan-mensuel",
      title: "Bilan Mensuel",
      category: "transversal",
      tokens_reward: 50,
      recurrence: "monthly",
      description: "Rédige ton bilan mensuel du cycle",
      active: true,
    },
    {
      slug: "aurora-session",
      title: "Session AURORA",
      category: "pilier",
      tokens_reward: 15,
      recurrence: "daily",
      description: "Complète une session AURORA OMEGA",
      active: true,
    },
    {
      slug: "luna-dialogue",
      title: "Dialogue LUNA",
      category: "pilier",
      tokens_reward: 10,
      recurrence: "daily",
      description: "Converse avec LUNA",
      active: true,
    },
    {
      slug: "cycle-suivi",
      title: "Suivi Cycle",
      category: "pilier",
      tokens_reward: 5,
      recurrence: "daily",
      description: "Note les données de ton cycle",
      active: true,
    },
    {
      slug: "aurora-binaural",
      title: "Audio Binaural",
      category: "pilier",
      tokens_reward: 10,
      recurrence: "daily",
      description: "Écoute 10 minutes de sons binauraux",
      active: true,
    },
    {
      slug: "luna-faq",
      title: "Question LUNA",
      category: "pilier",
      tokens_reward: 5,
      recurrence: "daily",
      description: "Pose une question à LUNA",
      active: true,
    },
    {
      slug: "phase-lecture",
      title: "Lecture de Phase",
      category: "pilier",
      tokens_reward: 8,
      recurrence: "daily",
      description: "Lis tes recommandations de phase",
      active: true,
    },
    {
      slug: "aurora-7jours",
      title: "7 Sessions AURORA",
      category: "pilier",
      tokens_reward: 100,
      recurrence: "weekly",
      description: "7 sessions AURORA en une semaine",
      active: true,
    },
    {
      slug: "cercle-participation",
      title: "Cercle d'Intention",
      category: "communautaire",
      tokens_reward: 20,
      recurrence: "weekly",
      description: "Participe à un Cercle d'Intention",
      active: true,
    },
    {
      slug: "communaute-partage",
      title: "Partage Communauté",
      category: "communautaire",
      tokens_reward: 10,
      recurrence: "daily",
      description: "Partage un témoignage anonyme",
      active: true,
    },
    {
      slug: "communaute-like",
      title: "Soutien Collectif",
      category: "communautaire",
      tokens_reward: 3,
      recurrence: "daily",
      description: "Encourage 3 témoignages",
      active: true,
    },
    {
      slug: "parrainage-actif",
      title: "Parrainage Actif",
      category: "communautaire",
      tokens_reward: 50,
      recurrence: "once",
      description: "Invite ta première filleule",
      active: true,
    },
    {
      slug: "don-asso",
      title: "Don à l'Asso",
      category: "communautaire",
      tokens_reward: 30,
      recurrence: "monthly",
      description: "Effectue un don solidaire",
      active: true,
    },
    {
      slug: "defi-7jours-aurora",
      title: "Défi 7j AURORA",
      category: "special",
      tokens_reward: 150,
      recurrence: "once",
      description: "7 sessions AURORA consécutives",
      active: true,
    },
    {
      slug: "defi-lune-pleine",
      title: "Rituel Lune Pleine",
      category: "special",
      tokens_reward: 75,
      recurrence: "monthly",
      description: "Rituel spécial pleine lune",
      active: true,
    },
    {
      slug: "defi-equinoxe",
      title: "Défi Équinoxe",
      category: "special",
      tokens_reward: 200,
      recurrence: "once",
      description: "Rituel d'équinoxe réalisé",
      active: true,
    },
    {
      slug: "defi-nouveau-cycle",
      title: "Nouveau Cycle",
      category: "special",
      tokens_reward: 100,
      recurrence: "monthly",
      description: "Commence un nouveau cycle conscient",
      active: true,
    },
    {
      slug: "v3-terra-nova",
      title: "Terra Nova (V3)",
      category: "v3",
      tokens_reward: 500,
      recurrence: "once",
      description: "Rejoins le réseau Terra Nova",
      active: false,
    },
    {
      slug: "v3-graines-echange",
      title: "Échange de Graines (V3)",
      category: "v3",
      tokens_reward: 0,
      recurrence: "once",
      description: "Échange tes premières Graines",
      active: false,
    },
  ];

  const result = await sql`
    INSERT INTO kaia.karma_games ${sql(
      games,
      "slug",
      "title",
      "category",
      "description",
      "tokens_reward",
      "recurrence",
      "active"
    )}
    ON CONFLICT (slug) DO NOTHING
    RETURNING slug
  `;


  await sql.end();
}

run().catch(console.error);
